# <b>Master Project - Analysis Notebook</b> 

## <i>Coping mechanisms of customers in relation to data collection methods in public personalized advertising</i>

ⓘ Below you can find compiled the code used to transform, clean and conduct analysis on the data gathered from a state-of-the-art survey. The survey and code was written by student <b> Viktor Varga </b> with the help of ChatGPT (mentioned in comments when used).

## 1. Importing and cleaning

In [1]:
# Modules
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
# Functions
from scipy.stats import ttest_rel, ttest_ind
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [2]:
# Importing Data
data_text = pd.read_csv("C:/Users/Trabala/Desktop/DDB/Master Project/Results/Survey_August_Text.csv")
data_num = pd.read_csv("C:/Users/Trabala/Desktop/DDB/Master Project/Results/Survey_August_Numeric.csv")

In [3]:
# Printing..
data_text

StartDate  \
0                                          Start Date   
1   {"ImportId":"startDate","timeZone":"Europe/Ber...   
2                                 2023-08-15 11:32:16   
3                                 2023-08-15 11:56:07   
4                                 2023-08-15 11:57:17   
..                                                ...   
92                                2023-08-16 15:53:36   
93                                2023-08-17 10:35:38   
94                                2023-08-18 23:32:55   
95                                2023-08-26 12:02:49   
96                                2023-08-26 14:43:02   

                                              EndDate                 Status  \
0                                            End Date          Response Type   
1   {"ImportId":"endDate","timeZone":"Europe/Berlin"}  {"ImportId":"status"}   
2                                 2023-08-15 11:40:18             IP Address   
3                                 2023-08-15 12:00:02             IP Address   
4                                 2023-08-15 12:01:34             IP Address   
..                                                ...                    ...   
92                                2023-08-16 15:54:21             IP Address   
93                                2023-08-17 10:36:20             IP Address   
94                                2023-08-18 23:33:36             IP Address   
95                                2023-08-26 12:04:58             IP Address   
96                                2023-08-26 14:45:18             IP Address   

                   IPAddress                 Progress  \
0                 IP Address                 Progress   
1   {"ImportId":"ipAddress"}  {"ImportId":"progress"}   
2             194.154.245.88                      100   
3               46.34.244.51                      100   
4             91.127.238.155                      100   
..                       ...                      ...   
92            89.205.133.230                       25   
93             91.127.80.160                       25   
94            145.224.109.25                       70   
95            145.224.109.25                      100   
96            145.224.109.25                      100   

      Duration (in seconds)                 Finished  \
0     Duration (in seconds)                 Finished   
1   {"ImportId":"duration"}  {"ImportId":"finished"}   
2                       481                     True   
3                       234                     True   
4                       257                     True   
..                      ...                      ...   
92                       44                    False   
93                       42                    False   
94                       40                    False   
95                      128                     True   
96                      136                     True   

                                         RecordedDate  \
0                                       Recorded Date   
1   {"ImportId":"recordedDate","timeZone":"Europe/...   
2                                 2023-08-15 11:40:19   
3                                 2023-08-15 12:00:03   
4                                 2023-08-15 12:01:35   
..                                                ...   
92                                2023-08-23 15:54:22   
93                                2023-08-24 10:36:25   
94                                2023-08-25 23:33:40   
95                                2023-08-26 12:04:59   
96                                2023-08-26 14:45:19   

                  ResponseId                 RecipientLastName  ...  \
0                Response ID               Recipient Last Name  ...   
1   {"ImportId":"_recordId"}  {"ImportId":"recipientLastName"}  ...   
2          R_33ansmY67no3RKN                               NaN  ...   
3          R_2P50BFiax5qSAly                               NaN  ...   


### Tidying the dataset...

### <b>A series of cleaning lines of code first had to be applied to transform the data so it is able to be disected, split and compared</b>

1. Filtering out unfinished survey reponses
2. Dropping non-relevant columns
3. Merging the text and number based cvs

In [4]:
# Printing continued...
data_num

StartDate  \
0                                          Start Date   
1   {"ImportId":"startDate","timeZone":"Europe/Ber...   
2                                 2023-08-15 11:32:16   
3                                 2023-08-15 11:56:07   
4                                 2023-08-15 11:57:17   
..                                                ...   
92                                2023-08-16 15:53:36   
93                                2023-08-17 10:35:38   
94                                2023-08-18 23:32:55   
95                                2023-08-26 12:02:49   
96                                2023-08-26 14:43:02   

                                              EndDate                 Status  \
0                                            End Date          Response Type   
1   {"ImportId":"endDate","timeZone":"Europe/Berlin"}  {"ImportId":"status"}   
2                                 2023-08-15 11:40:18                      0   
3                                 2023-08-15 12:00:02                      0   
4                                 2023-08-15 12:01:34                      0   
..                                                ...                    ...   
92                                2023-08-16 15:54:21                      0   
93                                2023-08-17 10:36:20                      0   
94                                2023-08-18 23:33:36                      0   
95                                2023-08-26 12:04:58                      0   
96                                2023-08-26 14:45:18                      0   

                   IPAddress                 Progress  \
0                 IP Address                 Progress   
1   {"ImportId":"ipAddress"}  {"ImportId":"progress"}   
2             194.154.245.88                      100   
3               46.34.244.51                      100   
4             91.127.238.155                      100   
..                       ...                      ...   
92            89.205.133.230                       25   
93             91.127.80.160                       25   
94            145.224.109.25                       70   
95            145.224.109.25                      100   
96            145.224.109.25                      100   

      Duration (in seconds)                 Finished  \
0     Duration (in seconds)                 Finished   
1   {"ImportId":"duration"}  {"ImportId":"finished"}   
2                       481                        1   
3                       234                        1   
4                       257                        1   
..                      ...                      ...   
92                       44                        0   
93                       42                        0   
94                       40                        0   
95                      128                        1   
96                      136                        1   

                                         RecordedDate  \
0                                       Recorded Date   
1   {"ImportId":"recordedDate","timeZone":"Europe/...   
2                                 2023-08-15 11:40:19   
3                                 2023-08-15 12:00:03   
4                                 2023-08-15 12:01:35   
..                                                ...   
92                                2023-08-23 15:54:22   
93                                2023-08-24 10:36:25   
94                                2023-08-25 23:33:40   
95                                2023-08-26 12:04:59   
96                                2023-08-26 14:45:19   

                  ResponseId                 RecipientLastName  ...  \
0                Response ID               Recipient Last Name  ...   
1   {"ImportId":"_recordId"}  {"ImportId":"recipientLastName"}  ...   
2          R_33ansmY67no3RKN                               NaN  ...   
3          R_2P50BFiax5qSAly                               NaN  ...   


In [5]:
# Filtering unfinished surveys
finished_data_text = data_text[data_text['Finished'] != 'False']
finished_data_num = data_num[data_num['Finished'] != 'False']

In [6]:
# Printing columns to drop
data_text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 52 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   StartDate              97 non-null     object
 1   EndDate                97 non-null     object
 2   Status                 97 non-null     object
 3   IPAddress              97 non-null     object
 4   Progress               97 non-null     object
 5   Duration (in seconds)  97 non-null     object
 6   Finished               97 non-null     object
 7   RecordedDate           97 non-null     object
 8   ResponseId             97 non-null     object
 9   RecipientLastName      2 non-null      object
 10  RecipientFirstName     2 non-null      object
 11  RecipientEmail         2 non-null      object
 12  ExternalReference      2 non-null      object
 13  LocationLatitude       80 non-null     object
 14  LocationLongitude      80 non-null     object
 15  DistributionChannel    97

In [7]:
# Defining columns to drop
columns_to_drop = ['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress', 
                   'Duration (in seconds)', 'ExternalReference', 'Finished', 'RecordedDate', 'RecipientFirstName',
                   'RecipientLastName', 'RecipientEmail', 'LocationLatitude', 
                   'LocationLongitude', 'DistributionChannel', 'UserLanguage']

In [8]:
# Droping said columns
filtered_data_text = finished_data_text.drop(columns=columns_to_drop)
filtered_data_num = finished_data_num.drop(columns=columns_to_drop)

In [9]:
# Observing
filtered_data_text

ResponseId                               Q1  \
0                Response ID  Please indicate your age group:   
1   {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
2          R_33ansmY67no3RKN                          18 - 24   
3          R_2P50BFiax5qSAly                          25 - 34   
4          R_10BgiVtu9sGveBS                          25 - 34   
..                       ...                              ...   
76         R_2vdjdFUkYWwdOki                          25 - 34   
77         R_BPq1Lvk0HUzl3tD                          18 - 24   
78         R_BriPmN2wELRwAet                          45 - 54   
95         R_2dsdedJjCrVL8ew                          25 - 34   
96         R_2VyE3lVoeS8d6yE                          18 - 24   

                             Q2                            Q3  \
0   Please specify your gender:             List of Countries   
1           {"ImportId":"QID2"}  {"ImportId":"QID1212994509"}   
2                        Female                      Slovakia   
3                          Male                      Slovakia   
4                          Male                         Niger   
..                          ...                           ...   
76                         Male                      Slovakia   
77                       Female                Czech Republic   
78                       Female                      Slovakia   
95                         Male                      Slovakia   
96                         Male                      Slovakia   

                                                   Q4  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                    Bachelor's degree (e.g. BA, BSc)   
3                      Master's degree (e.g. MA, MSc)   
4                               Less than high school   
..                                                ...   
76                   Bachelor's degree (e.g. BA, BSc)   
77                               High school graduate   
78                     Master's degree (e.g. MA, MSc)   
95                   Bachelor's degree (e.g. BA, BSc)   
96                   Bachelor's degree (e.g. BA, BSc)   

                                                 Q4.1  \
0   How familiar are you with the concept of perso...   
1                                 {"ImportId":"QID4"}   
2                                 Moderately familiar   
3                                   Slightly familiar   
4                                  Extremely familiar   
..                                                ...   
76                                Moderately familiar   
77                                Moderately familiar   
78                                Moderately familiar   
95                                      Very familiar   
96                                      Very familiar   

                                                 Q5_1  \
0   How much do you agree with the following state...   
1                               {"ImportId":"QID7_1"}   
2                                      Strongly agree   
3                                      Somewhat agree   
4                                      Strongly agree   
..                                                ...   
76                                     Somewhat agree   
77                                     Somewhat agree   
78                         Neither agree nor disagree   
95                                     Strongly agree   
96                                     Somewhat agree   

                                                 Q5_2  \
0   How much do you agree with the following state...   
1                               {"ImportId":"QID7_2"}   
2                                      Strongly agree   
3                                      Somewhat agree   
4                                      Strongly agree   
..                                                ...   
76

In [10]:
# Observing
filtered_data_num

ResponseId                               Q1  \
0                Response ID  Please indicate your age group:   
1   {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
2          R_33ansmY67no3RKN                                2   
3          R_2P50BFiax5qSAly                                3   
4          R_10BgiVtu9sGveBS                                3   
..                       ...                              ...   
92         R_2CBN3qa84HMx0V3                                5   
93         R_2uL1UsSkVmCXcq2                                2   
94         R_9Z9XjGViE7jXasp                                2   
95         R_2dsdedJjCrVL8ew                                3   
96         R_2VyE3lVoeS8d6yE                                2   

                             Q2                            Q3  \
0   Please specify your gender:             List of Countries   
1           {"ImportId":"QID2"}  {"ImportId":"QID1212994509"}   
2                             2                           157   
3                             1                           157   
4                             1                           125   
..                          ...                           ...   
92                            2                           122   
93                            2                           157   
94                            4                             4   
95                            1                           157   
96                            1                           157   

                                                   Q4  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                                                   4   
3                                                   5   
4                                                   1   
..                                                ...   
92                                                  6   
93                                                  5   
94                                                  2   
95                                                  4   
96                                                  4   

                                                 Q4.1  \
0   How familiar are you with the concept of perso...   
1                                 {"ImportId":"QID4"}   
2                                                   3   
3                                                   2   
4                                                   5   
..                                                ...   
92                                                NaN   
93                                                NaN   
94                                                  3   
95                                                  4   
96                                                  4   

                                                 Q5_1  \
0   How much do you agree with the following state...   
1                               {"ImportId":"QID7_1"}   
2                                                   5   
3                                                   4   
4                                                   5   
..                                                ...   
92                                                NaN   
93                                                NaN   
94                                                  1   
95                                                  5   
96                                                  4   

                                                 Q5_2  \
0   How much do you agree with the following state...   
1                               {"ImportId":"QID7_2"}   
2                                                   5   
3                                                   4   
4                                                   5   
..                                                ...   
92

In [11]:
# Merging the data on ResponseId and creating a distinguishable label for the column names
merged_data = pd.merge(filtered_data_num, filtered_data_text, on='ResponseId', suffixes=('_num', '_text'))
# Prinitng merged dataset
merged_data

ResponseId                           Q1_num  \
0                Response ID  Please indicate your age group:   
1   {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
2          R_33ansmY67no3RKN                                2   
3          R_2P50BFiax5qSAly                                3   
4          R_10BgiVtu9sGveBS                                3   
..                       ...                              ...   
76         R_2vdjdFUkYWwdOki                                3   
77         R_BPq1Lvk0HUzl3tD                                2   
78         R_BriPmN2wELRwAet                                5   
79         R_2dsdedJjCrVL8ew                                3   
80         R_2VyE3lVoeS8d6yE                                2   

                         Q2_num                        Q3_num  \
0   Please specify your gender:             List of Countries   
1           {"ImportId":"QID2"}  {"ImportId":"QID1212994509"}   
2                             2                           157   
3                             1                           157   
4                             1                           125   
..                          ...                           ...   
76                            1                           157   
77                            2                            45   
78                            2                           157   
79                            1                           157   
80                            1                           157   

                                               Q4_num  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                                                   4   
3                                                   5   
4                                                   1   
..                                                ...   
76                                                  4   
77                                                  2   
78                                                  5   
79                                                  4   
80                                                  4   

                                             Q4.1_num  \
0   How familiar are you with the concept of perso...   
1                                 {"ImportId":"QID4"}   
2                                                   3   
3                                                   2   
4                                                   5   
..                                                ...   
76                                                  3   
77                                                  3   
78                                                  3   
79                                                  4   
80                                                  4   

                                             Q5_1_num  \
0   How much do you agree with the following state...   
1                               {"ImportId":"QID7_1"}   
2                                                   5   
3                                                   4   
4                                                   5   
..                                                ...   
76                                                  4   
77                                                  4   
78                                                  3   
79                                                  5   
80                                                  4   

                                             Q5_2_num  \
0   How much do you agree with the following state...   
1                               {"ImportId":"QID7_2"}   
2                                                   5   
3                                                   4   
4                                                   5   
..                                                ...   
76

In [12]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81 entries, 0 to 80
Data columns (total 71 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ResponseId  81 non-null     object
 1   Q1_num      81 non-null     object
 2   Q2_num      81 non-null     object
 3   Q3_num      81 non-null     object
 4   Q4_num      81 non-null     object
 5   Q4.1_num    81 non-null     object
 6   Q5_1_num    81 non-null     object
 7   Q5_2_num    81 non-null     object
 8   Q5_3_num    81 non-null     object
 9   Q5_4_num    81 non-null     object
 10  Q6A_1_num   42 non-null     object
 11  Q6A_2_num   42 non-null     object
 12  Q6A_3_num   42 non-null     object
 13  Q6A_4_num   42 non-null     object
 14  Q6A_5_num   42 non-null     object
 15  Q6A_6_num   42 non-null     object
 16  Q7A_1_num   42 non-null     object
 17  Q7A_2_num   42 non-null     object
 18  Q7A_3_num   42 non-null     object
 19  Q7A_4_num   42 non-null     object
 20  Q7A_5_num   

### Transforming column names...

In [13]:
# Extracting base names of the columns
base_cols = [col.replace('_num', '').replace('_text', '') for col in merged_data.columns]

# Removing duplicates while preserving order
base_cols = list(dict.fromkeys(base_cols))

# Generating the desired column order #ChatGPT
desired_order = []
for base_col in base_cols:
    if base_col != 'ResponseId':
        desired_order.append(base_col + '_text')
        desired_order.append(base_col + '_num')
    else:
        desired_order.append(base_col)

# Reordering the dataframe columns based on the generated order
merged_data = merged_data[desired_order]

In [14]:
# Set the display option to show all columns
pd.set_option('display.max_columns', None)

Lovely, now change the column names to these: ResponseId stays the same, Q1_text_demo
Q1_num_demo
Q2_text_demo
Q2_num_demo
Q3_text_demo
Q3_num_demo
Q4_text_demo
Q4_num_demo
Q5_text_gen
Q5_num_gen
Q6_text_gen
Q6_num_gen

In [15]:
merged_data

ResponseId                          Q1_text  \
0                Response ID  Please indicate your age group:   
1   {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
2          R_33ansmY67no3RKN                          18 - 24   
3          R_2P50BFiax5qSAly                          25 - 34   
4          R_10BgiVtu9sGveBS                          25 - 34   
..                       ...                              ...   
76         R_2vdjdFUkYWwdOki                          25 - 34   
77         R_BPq1Lvk0HUzl3tD                          18 - 24   
78         R_BriPmN2wELRwAet                          45 - 54   
79         R_2dsdedJjCrVL8ew                          25 - 34   
80         R_2VyE3lVoeS8d6yE                          18 - 24   

                             Q1_num                      Q2_text  \
0   Please indicate your age group:  Please specify your gender:   
1               {"ImportId":"QID1"}          {"ImportId":"QID2"}   
2                                 2                       Female   
3                                 3                         Male   
4                                 3                         Male   
..                              ...                          ...   
76                                3                         Male   
77                                2                       Female   
78                                5                       Female   
79                                3                         Male   
80                                2                         Male   

                         Q2_num                       Q3_text  \
0   Please specify your gender:             List of Countries   
1           {"ImportId":"QID2"}  {"ImportId":"QID1212994509"}   
2                             2                      Slovakia   
3                             1                      Slovakia   
4                             1                         Niger   
..                          ...                           ...   
76                            1                      Slovakia   
77                            2                Czech Republic   
78                            2                      Slovakia   
79                            1                      Slovakia   
80                            1                      Slovakia   

                          Q3_num  \
0              List of Countries   
1   {"ImportId":"QID1212994509"}   
2                            157   
3                            157   
4                            125   
..                           ...   
76                           157   
77                            45   
78                           157   
79                           157   
80                           157   

                                              Q4_text  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                    Bachelor's degree (e.g. BA, BSc)   
3                      Master's degree (e.g. MA, MSc)   
4                               Less than high school   
..                                                ...   
76                   Bachelor's degree (e.g. BA, BSc)   
77                               High school graduate   
78                     Master's degree (e.g. MA, MSc)   
79                   Bachelor's degree (e.g. BA, BSc)   
80                   Bachelor's degree (e.g. BA, BSc)   

                                               Q4_num  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                                                   4   
3                                                   5   
4                                                   1   
..                                                ...   
76                                                  4   
77                                                  2   
78      

In [16]:
# Defining the new column names                       # Source: ChatGPT 
new_column_names = [
    'ResponseId',
    'Q1_text_demo', 'Q1_num_demo', 'Q2_text_demo', 'Q2_num_demo', 'Q3_text_demo', 'Q3_num_demo', 'Q4_text_demo', 'Q4_num_demo',
    'Q5_text_gen', 'Q5_num_gen', 'Q6_text_gen', 'Q6_num_gen', 'Q7_text_gen', 'Q7_num_gen', 'Q8_text_gen', 'Q8_num_gen', 'Q9_text_gen', 'Q9_num_gen',
    'Q10A_text_use', 'Q10A_num_use', 'Q11A_text_use', 'Q11A_num_use', 'Q12A_text_use', 'Q12A_num_use', 'Q13A_text_use', 'Q13A_num_use', 'Q14A_text_use', 'Q14A_num_use', 'Q15A_text_use', 'Q15A_num_use',
    'Q16A_text_priv', 'Q16A_num_priv', 'Q17A_text_priv', 'Q17A_num_priv', 'Q18A_text_priv', 'Q18A_num_priv', 'Q19A_text_priv', 'Q19A_num_priv', 'Q20A_text_priv', 'Q20A_num_priv',
    'Q21A_text_data', 'Q21A_num_data', 'Q22A_text_rew', 'Q22A_num_rew',
    'Q10B_text_use', 'Q10B_num_use', 'Q11B_text_use', 'Q11B_num_use', 'Q12B_text_use', 'Q12B_num_use', 'Q13B_text_use', 'Q13B_num_use', 'Q14B_text_use', 'Q14B_num_use', 'Q15B_text_use', 'Q15B_num_use',
    'Q16B_text_priv', 'Q16B_num_priv', 'Q17B_text_priv', 'Q17B_num_priv', 'Q18B_text_priv', 'Q18B_num_priv', 'Q19B_text_priv', 'Q19B_num_priv', 'Q20B_text_priv', 'Q20B_num_priv',
    'Q21B_text_data', 'Q21B_num_data', 'Q22B_text_rew', 'Q22B_num_rew'
]

In [17]:
# Renaming the columns
merged_data.columns = new_column_names

In [18]:
merged_data

ResponseId                     Q1_text_demo  \
0                Response ID  Please indicate your age group:   
1   {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
2          R_33ansmY67no3RKN                          18 - 24   
3          R_2P50BFiax5qSAly                          25 - 34   
4          R_10BgiVtu9sGveBS                          25 - 34   
..                       ...                              ...   
76         R_2vdjdFUkYWwdOki                          25 - 34   
77         R_BPq1Lvk0HUzl3tD                          18 - 24   
78         R_BriPmN2wELRwAet                          45 - 54   
79         R_2dsdedJjCrVL8ew                          25 - 34   
80         R_2VyE3lVoeS8d6yE                          18 - 24   

                        Q1_num_demo                 Q2_text_demo  \
0   Please indicate your age group:  Please specify your gender:   
1               {"ImportId":"QID1"}          {"ImportId":"QID2"}   
2                                 2                       Female   
3                                 3                         Male   
4                                 3                         Male   
..                              ...                          ...   
76                                3                         Male   
77                                2                       Female   
78                                5                       Female   
79                                3                         Male   
80                                2                         Male   

                    Q2_num_demo                  Q3_text_demo  \
0   Please specify your gender:             List of Countries   
1           {"ImportId":"QID2"}  {"ImportId":"QID1212994509"}   
2                             2                      Slovakia   
3                             1                      Slovakia   
4                             1                         Niger   
..                          ...                           ...   
76                            1                      Slovakia   
77                            2                Czech Republic   
78                            2                      Slovakia   
79                            1                      Slovakia   
80                            1                      Slovakia   

                     Q3_num_demo  \
0              List of Countries   
1   {"ImportId":"QID1212994509"}   
2                            157   
3                            157   
4                            125   
..                           ...   
76                           157   
77                            45   
78                           157   
79                           157   
80                           157   

                                         Q4_text_demo  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                    Bachelor's degree (e.g. BA, BSc)   
3                      Master's degree (e.g. MA, MSc)   
4                               Less than high school   
..                                                ...   
76                   Bachelor's degree (e.g. BA, BSc)   
77                               High school graduate   
78                     Master's degree (e.g. MA, MSc)   
79                   Bachelor's degree (e.g. BA, BSc)   
80                   Bachelor's degree (e.g. BA, BSc)   

                                          Q4_num_demo  \
0   Please indicate your highest level of educatio...   
1                                 {"ImportId":"QID3"}   
2                                                   4   
3                                                   5   
4                                                   1   
..                                                ...   
76                                                  4   
77                                                  2   
78      

In [19]:
# Splitting the dataset based on the presence of NaN values in treatment A or B columns
data_treatment_A = merged_data[merged_data['Q10A_num_use'].notna()].copy()
data_treatment_B = merged_data[merged_data['Q10B_num_use'].notna()].copy()

In [20]:
data_treatment_A

ResponseId                     Q1_text_demo  \
0                Response ID  Please indicate your age group:   
1   {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
3          R_2P50BFiax5qSAly                          25 - 34   
4          R_10BgiVtu9sGveBS                          25 - 34   
6          R_0IzxnJkKlYsL2CZ                          45 - 54   
7          R_12JQ6Oqs8oVy8N4                          25 - 34   
10         R_UDsvun7YJiU8XOV                          25 - 34   
12         R_1hW7217wTXnbVis                          18 - 24   
14         R_2b3OIsBI74Whfge                          25 - 34   
16         R_VPzqRUghYEmK5ZT                          18 - 24   
17         R_dj9dwHCFFUViAlr                          18 - 24   
20         R_26hEULOxCNIq4Uq                          25 - 34   
21         R_33jQFD4heG49nhT                          25 - 34   
23         R_3D8iJocCDWaeHbN                          25 - 34   
25         R_2YlIv6zvkama7ok                          25 - 34   
27         R_1reLjdajejJYdxz                          25 - 34   
30         R_3JDaR8Ls0g0Lp9d                          25 - 34   
32         R_3My6OJ6O7Qi9K5g                          25 - 34   
33         R_1H0jRe0hDL6LHuN                          18 - 24   
36         R_2bKk3ZRZ2aeqFW2                          25 - 34   
37         R_1hGshFyOfOoMNF5                          25 - 34   
38         R_2S79sBeDxo7ixb6                          25 - 34   
41         R_3kMwOMXnu5tmcHK                          45 - 54   
42         R_24uPqIi4Yt0i8hx                          25 - 34   
44         R_1jg50KblYmUiWSE                          25 - 34   
46         R_e5peeuWARDPljGx                          18 - 24   
48         R_28S9XuURSf44q5f                          25 - 34   
49         R_DnMWPMMbvVgqeZP                          18 - 24   
51         R_2UbbhlEufRVPASR                          18 - 24   
55         R_31NvIW4IzKAZdoW                          55 - 64   
58         R_d6eL3OQ0Zp8cf4d                          25 - 34   
59         R_3PXFKAnFNHSt3Lv                          18 - 24   
62         R_3O99kaOnQmbWnbO                          35 - 44   
65         R_umj5cpCMR8WfYlj                          18 - 24   
66         R_2QDqZOHabnMXUpc                          18 - 24   
68         R_3KDRnZnhu6MLNw8                          25 - 34   
69         R_30kpEdGqF0NKfq5                          18 - 24   
72         R_3M58P8By9n6F4l0                          45 - 54   
73         R_3O6MzEaIXXX2eZs                          25 - 34   
75         R_3G8je3roSrJRCs7                          18 - 24   
77         R_BPq1Lvk0HUzl3tD                          18 - 24   
79         R_2dsdedJjCrVL8ew                          25 - 34   

                        Q1_num_demo                 Q2_text_demo  \
0   Please indicate your age group:  Please specify your gender:   
1               {"ImportId":"QID1"}          {"ImportId":"QID2"}   
3                                 3                         Male   
4                                 3                         Male   
6                                 5                       Female   
7                                 3                       Female   
10                                3                       Female   
12                                2                         Male   
14                                3                         Male   
16                                2                       Female   
17                                2                         Male   
20                                3                         Male   
21                                3                         Male   
23                                3                         Male   
25                                3                         Male   
27                                3                         Male   
30                                3                         Male  

In [21]:
# Extracting relevant columns for privacy concerns
privacy_cols_A = ['Q16A_num_priv', 'Q17A_num_priv', 'Q18A_num_priv', 'Q19A_num_priv', 'Q20A_num_priv']
privacy_cols_B = [col.replace('A', 'B') for col in privacy_cols_A]

# Extracting columns for perceived usefulness
usefulness_cols_A = ['Q10A_num_use', 'Q11A_num_use', 'Q12A_num_use', 'Q13A_num_use', 'Q14A_num_use', 'Q15A_num_use']
usefulness_cols_B = [col.replace('A', 'B') for col in usefulness_cols_A]

# Columns for positive experience with personalization
positive_experience_cols = ['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']

# Transform data to numeric for Treatment A
data_treatment_A[privacy_cols_A] = data_treatment_A[privacy_cols_A].apply(pd.to_numeric, errors='coerce')
data_treatment_A[usefulness_cols_A] = data_treatment_A[usefulness_cols_A].apply(pd.to_numeric, errors='coerce')
data_treatment_A[positive_experience_cols] = data_treatment_A[positive_experience_cols].apply(pd.to_numeric, errors='coerce')

# Transform data to numeric for Treatment B
data_treatment_B[privacy_cols_B] = data_treatment_B[privacy_cols_B].apply(pd.to_numeric, errors='coerce')
data_treatment_B[usefulness_cols_B] = data_treatment_B[usefulness_cols_B].apply(pd.to_numeric, errors='coerce')
data_treatment_B[positive_experience_cols] = data_treatment_B[positive_experience_cols].apply(pd.to_numeric, errors='coerce')

In [22]:
# Dropping columns related to the other treatment for A
columns_B = [col for col in merged_data.columns if 'B_' in col]
data_treatment_A.drop(columns=columns_B, inplace=True)

In [23]:
# Dropping columns related to the other treatment for B
columns_A = [col for col in merged_data.columns if 'A_' in col]
data_treatment_B.drop(columns=columns_A, inplace=True)

In [24]:
# Finding out the number of observations for each treatment
data_treatment_A.shape

(42, 45)

In [25]:
# Finding out the number of observations for each treatment
data_treatment_B.shape

(41, 45)

## 3. Basic Analysis 

### Chronbach's Alpha

In [26]:
# Creating copies of the dataframes for Cronbach's Alpha computation
data_treatment_A_alpha = data_treatment_A.iloc[2:].copy()
data_treatment_B_alpha = data_treatment_B.iloc[2:].copy()

In [27]:
# Converting the relevant columns to numeric
data_treatment_A_alpha = data_treatment_A_alpha.apply(pd.to_numeric, errors='coerce')
data_treatment_B_alpha = data_treatment_B_alpha.apply(pd.to_numeric, errors='coerce')

In [28]:
# Making a function to calculate cronbachs_alpha #ChatGPT
def cronbach_alpha(df):
    k = df.shape[1]
    y = df.sum(axis=1)
    total_var = y.var(ddof=1)
    variances = df.var(axis=0, ddof=1)
    sum_var = variances.sum()
    alpha = (k / (k - 1)) * (1 - (sum_var / total_var))
    return alpha

In [29]:
# Perceived usefulness for treatment A and B
usefulness_cols_A = [f"Q{i}A_num_use" for i in range(10, 16)]
usefulness_cols_B = [f"Q{i}B_num_use" for i in range(10, 16)]

alpha_usefulness_A = cronbach_alpha(data_treatment_A_alpha[usefulness_cols_A])
alpha_usefulness_B = cronbach_alpha(data_treatment_B_alpha[usefulness_cols_B])

print(f"Cronbach's Alpha for Perceived Usefulness (Treatment A): {alpha_usefulness_A}")
print(f"Cronbach's Alpha for Perceived Usefulness (Treatment B): {alpha_usefulness_B}")

# Privacy concern for treatment A and B
privacy_cols_A = [f"Q{i}A_num_priv" for i in range(16, 21)]
privacy_cols_B = [f"Q{i}B_num_priv" for i in range(16, 21)]

alpha_privacy_A = cronbach_alpha(data_treatment_A_alpha[privacy_cols_A])
alpha_privacy_B = cronbach_alpha(data_treatment_B_alpha[privacy_cols_B])

print(f"Cronbach's Alpha for Privacy Concern (Treatment A): {alpha_privacy_A}")
print(f"Cronbach's Alpha for Privacy Concern (Treatment B): {alpha_privacy_B}")

# Inclination towards personalization
inclination_cols = [f"Q{i}_num_gen" for i in range(6, 10)]

alpha_inclination_A = cronbach_alpha(data_treatment_A_alpha[inclination_cols])
alpha_inclination_B = cronbach_alpha(data_treatment_B_alpha[inclination_cols])

print(f"Cronbach's Alpha for Inclination Towards Personalization (Treatment A): {alpha_inclination_A}")
print(f"Cronbach's Alpha for Inclination Towards Personalization (Treatment B): {alpha_inclination_B}")


Cronbach's Alpha for Perceived Usefulness (Treatment A): 0.9325969475622067
Cronbach's Alpha for Perceived Usefulness (Treatment B): 0.9276358873608382
Cronbach's Alpha for Privacy Concern (Treatment A): 0.8624658038720541
Cronbach's Alpha for Privacy Concern (Treatment B): 0.9137073468934089
Cronbach's Alpha for Inclination Towards Personalization (Treatment A): 0.7932524862573956
Cronbach's Alpha for Inclination Towards Personalization (Treatment B): 0.7940547235671654


In [30]:
privacy_cols_A

['Q16A_num_priv',
 'Q17A_num_priv',
 'Q18A_num_priv',
 'Q19A_num_priv',
 'Q20A_num_priv']

In [31]:
data_treatment_B.head(4)

ResponseId                     Q1_text_demo  \
0               Response ID  Please indicate your age group:   
1  {"ImportId":"_recordId"}              {"ImportId":"QID1"}   
2         R_33ansmY67no3RKN                          18 - 24   
5         R_3MaDBsy327ArDfv                          25 - 34   

                       Q1_num_demo                 Q2_text_demo  \
0  Please indicate your age group:  Please specify your gender:   
1              {"ImportId":"QID1"}          {"ImportId":"QID2"}   
2                                2                       Female   
5                                3                         Male   

                   Q2_num_demo                  Q3_text_demo  \
0  Please specify your gender:             List of Countries   
1          {"ImportId":"QID2"}  {"ImportId":"QID1212994509"}   
2                            2                      Slovakia   
5                            1                      Slovakia   

                    Q3_num_demo  \
0             List of Countries   
1  {"ImportId":"QID1212994509"}   
2                           157   
5                           157   

                                        Q4_text_demo  \
0  Please indicate your highest level of educatio...   
1                                {"ImportId":"QID3"}   
2                   Bachelor's degree (e.g. BA, BSc)   
5                               High school graduate   

                                         Q4_num_demo  \
0  Please indicate your highest level of educatio...   
1                                {"ImportId":"QID3"}   
2                                                  4   
5                                                  2   

                                         Q5_text_gen  \
0  How familiar are you with the concept of perso...   
1                                {"ImportId":"QID4"}   
2                                Moderately familiar   
5                                  Slightly familiar   

                                          Q5_num_gen  \
0  How familiar are you with the concept of perso...   
1                                {"ImportId":"QID4"}   
2                                                  3   
5                                                  2   

                                         Q6_text_gen  Q6_num_gen  \
0  How much do you agree with the following state...         NaN   
1                              {"ImportId":"QID7_1"}         NaN   
2                                     Strongly agree         5.0   
5                                  Somewhat disagree         2.0   

                                         Q7_text_gen  Q7_num_gen  \
0  How much do you agree with the following state...         NaN   
1                              {"ImportId":"QID7_2"}         NaN   
2                                     Strongly agree         5.0   
5                                  Somewhat disagree         2.0   

                                         Q8_text_gen  Q8_num_gen  \
0  How much do you agree with the following state...         NaN   
1                              {"ImportId":"QID7_3"}         NaN   
2                                     Somewhat agree         4.0   
5                                  Somewhat disagree         2.0   

                                         Q9_text_gen  Q9_num_gen  \
0  How much do you agree with the following state...         NaN   
1                              {"ImportId":"QID7_4"}         NaN   
2                                     Strongly agree         5.0   
5                                  Somewhat disagree         2.0   

                                       Q10B_text_use  Q10B_num_use  \
0  Having imagined the above scenario please pick...           NaN   
1                             {"ImportId":"QID16_1"}           NaN   
2                                    Slightly likely           5.0   
5                                     Quite unlikely           2.0   

                        

### Influence of <b>age</b> on overall usefulness of either/both interfaces

In [32]:
# Splitting the dataset based on the presence of NaN values in treatment A or B columns
data_treatment_A = merged_data[merged_data['Q10A_num_use'].notna()].copy()
data_treatment_B = merged_data[merged_data['Q10B_num_use'].notna()].copy()

In [33]:
# Drop the first two rows from both DataFrames
data_treatment_A = data_treatment_A.iloc[2:]
data_treatment_B = data_treatment_B.iloc[2:]

In [34]:
# Dropping columns related to the other treatment for B
columns_A = [col for col in merged_data.columns if 'A_' in col]
data_treatment_B.drop(columns=columns_A, inplace=True)

# Dropping columns related to the other treatment for A
columns_B = [col for col in merged_data.columns if 'B_' in col]
data_treatment_A.drop(columns=columns_B, inplace=True)

In [35]:
# Converting the 'Q1_num_demo' column to integer type for both treatments
data_treatment_A['Q1_num_demo'] = data_treatment_A['Q1_num_demo'].astype(int)
data_treatment_B['Q1_num_demo'] = data_treatment_B['Q1_num_demo'].astype(int)
# Defining the question about age
age_col = 'Q1_num_demo' 


In [36]:
# Converting all columns with '_num_' in their names to numeric type for Treatment A, excluding specified columns
num_cols_A = [col for col in data_treatment_A.columns if '_num_' in col and col not in ['Q21A_num_data', 'Q22A_num_rew']]
data_treatment_A[num_cols_A] = data_treatment_A[num_cols_A].apply(pd.to_numeric, errors='coerce')

# Converting all columns with '_num_' in their names to numeric type for Treatment B, excluding specified columns
num_cols_B = [col for col in data_treatment_B.columns if '_num_' in col and col not in ['Q21B_num_data', 'Q22B_num_rew']]
data_treatment_B[num_cols_B] = data_treatment_B[num_cols_B].apply(pd.to_numeric, errors='coerce')


### First, Need to check the distribution of age groups and possibly group them 

In [37]:
# Age dist For treatment A
age_distribution_A = data_treatment_A[age_col].value_counts().sort_index()

# Age dist For treatment B
age_distribution_B = data_treatment_B[age_col].value_counts().sort_index()

print("Age distribution for Treatment A:")
print(age_distribution_A)
print("\nAge distribution for Treatment B:")
print(age_distribution_B)

Age distribution for Treatment A:
2    13
3    22
4     1
5     3
6     1
Name: Q1_num_demo, dtype: int64

Age distribution for Treatment B:
1     1
2    10
3    19
4     3
5     3
6     2
7     1
Name: Q1_num_demo, dtype: int64


In [38]:
# Defining function that groups the age differently
def regroup_age(age):
    if age in [1, 2]:
        return 'Gen Z'
    elif age in [3, 4]:
        return 'Millennials & Early Gen X'
    else:  # Combining age groups [5, 6, 7]
        return 'Late Gen X, Baby Boomers & Older'

# Apply the adjusted function to the age column for both treatments
data_treatment_A['Generation'] = data_treatment_A['Q1_num_demo'].apply(regroup_age)
data_treatment_B['Generation'] = data_treatment_B['Q1_num_demo'].apply(regroup_age)

# Checking the distribution for Treatment A
print("Age distribution for Treatment A:")
print(data_treatment_A['Generation'].value_counts())

# Checking the distribution for Treatment B
print("\nAge distribution for Treatment B:")
print(data_treatment_B['Generation'].value_counts())

Age distribution for Treatment A:
Millennials & Early Gen X           23
Gen Z                               13
Late Gen X, Baby Boomers & Older     4
Name: Generation, dtype: int64

Age distribution for Treatment B:
Millennials & Early Gen X           22
Gen Z                               11
Late Gen X, Baby Boomers & Older     6
Name: Generation, dtype: int64


 ### <b>ANOVA (Analysis of Variance)</b> is a statistical method used to test differences between two or more means. In this case, we want to see if there's a difference in perceived usefulness across different age groups. Each age group represents a different "mean" or average score of perceived usefulness.

 ### If age had no effect on perceived usefulness, we'd expect all age groups to have roughly the same average score. If age does have an effect, some age groups will have significantly higher or lower scores than others.

In [39]:
# Calculating AVG perceived usefulness for each respondent for Treatment A
usefulness_cols_A = ['Q10A_num_use', 'Q11A_num_use', 'Q12A_num_use', 'Q13A_num_use', 'Q14A_num_use', 'Q15A_num_use']
data_treatment_A['avg_usefulness_A'] = data_treatment_A[usefulness_cols_A].mean(axis=1)

# ANOVA for Treatment A
fvalue_A, pvalue_A = stats.f_oneway(
    data_treatment_A['avg_usefulness_A'][data_treatment_A['Generation'] == 'Gen Z'],
    data_treatment_A['avg_usefulness_A'][data_treatment_A['Generation'] == 'Millennials & Early Gen X'],
    data_treatment_A['avg_usefulness_A'][data_treatment_A['Generation'] == 'Late Gen X, Baby Boomers & Older']
)
print(f"ANOVA result for Treatment A: F={fvalue_A}, p={pvalue_A}")

ANOVA result for Treatment A: F=2.05384406129883, p=0.14261178499270058


In [40]:
# Calculate average perceived usefulness for each respondent for Treatment B
usefulness_cols_B = [col.replace('A', 'B') for col in usefulness_cols_A]
data_treatment_B['avg_usefulness_B'] = data_treatment_B[usefulness_cols_B].mean(axis=1)

# ANOVA for Treatment B
fvalue_B, pvalue_B = stats.f_oneway(
    data_treatment_B['avg_usefulness_B'][data_treatment_B['Generation'] == 'Gen Z'],
    data_treatment_B['avg_usefulness_B'][data_treatment_B['Generation'] == 'Millennials & Early Gen X'],
    data_treatment_B['avg_usefulness_B'][data_treatment_B['Generation'] == 'Late Gen X, Baby Boomers & Older']
)

print(f"ANOVA result for Treatment B: F={fvalue_B}, p={pvalue_B}")

ANOVA result for Treatment B: F=4.0759750149739045, p=0.025371550130030732


For the second treatment (B) The p-value is <b>0.02537</b>, which is less than <b>0.05</b>. This suggests that there is a statistically significant difference in perceived usefulness across the age groups for Treatment B. Given this result, we will to conduct post-hoc tests to determine which specific age groups differ from each other in their perceptions.

In [41]:
# Conducting Tukey's HSD post-hoc test for Treatment B
posthoc_B = pairwise_tukeyhsd(data_treatment_B['avg_usefulness_B'], data_treatment_B['Generation'])
print("Post-hoc results for Treatment B:")
print(posthoc_B)

Post-hoc results for Treatment B:
                          Multiple Comparison of Means - Tukey HSD, FWER=0.05                          
             group1                           group2              meandiff p-adj   lower  upper  reject
-------------------------------------------------------------------------------------------------------
                           Gen Z Late Gen X, Baby Boomers & Older   1.7879   0.07 -0.1198 3.6955  False
                           Gen Z        Millennials & Early Gen X   1.4773 0.0349  0.0892 2.8653   True
Late Gen X, Baby Boomers & Older        Millennials & Early Gen X  -0.3106 0.8997 -2.0418 1.4206  False
-------------------------------------------------------------------------------------------------------


Given the Tukey HSD results for Treatment B:

The post-hoc analysis using the Tukey HSD test revealed a statistically significant difference in perceived usefulness between the "Gen Z" group and the "Millennials & Early Gen X" group (p=0.0349). Specifically, the "Millennials & Early Gen X" group perceived the interface as more useful by an average difference of 1.4773 units compared to the "Gen Z" group.

However, there were no statistically significant differences in perceived usefulness between the "Gen Z" group and the "Late Gen X, Baby Boomers & Older" group (p=0.07), even though the p-value is close to the 0.05 threshold. Similarly, the difference between the "Late Gen X, Baby Boomers & Older" group and the "Millennials & Early Gen X" group was not statistically significant (p=0.8997).

In conclusion, The most notable finding is the significant difference between the "Gen Z" group and the "Millennials & Early Gen X" group. Specifically, the "Millennials & Early Gen X" group perceived the interface as more useful than the "Gen Z" group. This suggests that the younger generation (Gen Z) might have different expectations or criteria for what they consider a useful personalized ad interface compared to the slightly older generation (Millennials & Early Gen X).

## FURTHER DRILL-DOWN PERCEIVED PRIVACY CONCERN IN TREATMENT B ACROSS AGE GROUPS

In [42]:
# Computing average privacy concerns for each respondent in Treatment B
data_treatment_B['avg_privacy_concern'] = data_treatment_B[['Q16B_num_priv', 'Q17B_num_priv', 'Q18B_num_priv', 'Q19B_num_priv', 'Q20B_num_priv']].mean(axis=1)

In [43]:
fvalue, pvalue = stats.f_oneway(*[data_treatment_B['avg_privacy_concern'][data_treatment_B['Generation'] == gen] for gen in data_treatment_B['Generation'].unique()])

In [44]:
print(f"ANOVA result for Privacy Concerns across Age Groups in Treatment B: F={fvalue}, p={pvalue}")

ANOVA result for Privacy Concerns across Age Groups in Treatment B: F=0.4280837505689579, p=0.6550310692992913


In [45]:
# If p-value is less than 0.05, conduct post-hoc analysis
if pvalue < 0.05:
    from statsmodels.stats.multicomp import pairwise_tukeyhsd

    tukey_results = pairwise_tukeyhsd(data_treatment_B['avg_privacy_concern'], data_treatment_B['Generation'], alpha=0.05)
    print(tukey_results)

As a follow-up analysis in the context of Treatment B and, we sought to understand if different age groups exhibited varying levels of privacy concerns when exposed to the biometric scanning camera, representing explicit data collection. To this end, an ANOVA test was conducted to compare the average privacy concerns across the distinct age groups.

The ANOVA results yielded an F-statistic of 0.4281. Crucially, the p-value associated with this statistic was 0.6550, which is well above the conventional significance threshold of 0.05.

The high p-value suggests that there are no statistically significant differences in privacy concerns across the age groups in Treatment B. In other words, age does not appear to be a determining factor in how respondents perceive privacy issues in the context of explicit data collection through the biometric scanning camera. All age groups, whether younger or older, seem to have similar levels of privacy concerns when exposed to this particular data collection method. This finding challenges potential assumptions that older generations might have heightened privacy concerns due to unfamiliarity with technology or that younger generations, despite their tech-savviness, might be more cautious due to increased awareness of privacy issues. In the specific context of Treatment B, age does not seem to play a pivotal role in shaping privacy perceptions.

## Influence of <b>Education level</b> on overall perceived usefulness

In [46]:
# Changing datatype to int
data_treatment_A['Q4_num_demo'] = data_treatment_A['Q4_num_demo'].astype(int)
data_treatment_B['Q4_num_demo'] = data_treatment_B['Q4_num_demo'].astype(int)

In [47]:
# Checking Education level distribution first
print("Education distribution for Treatment A:")
print(data_treatment_A['Q4_num_demo'].value_counts().sort_index())

print("\nEducation distribution for Treatment B:")
print(data_treatment_B['Q4_num_demo'].value_counts().sort_index())

Education distribution for Treatment A:
1     2
2     5
3     5
4     9
5    19
Name: Q4_num_demo, dtype: int64

Education distribution for Treatment B:
1     1
2     4
3     2
4    12
5    17
6     3
Name: Q4_num_demo, dtype: int64


### ...Regrouping the education levels, like we did with age groups

In [48]:
# Defining a function to regroup education levels
def regroup_education(education_level):
    if education_level in [1, 2]:
        return 'Basic Education'
    elif education_level in [3, 4]:
        return 'Intermediate Education'
    else:
        return 'Advanced Education'

# Apply the function to the education column for both treatments
data_treatment_A['Education_Group'] = data_treatment_A['Q4_num_demo'].apply(regroup_education)
data_treatment_B['Education_Group'] = data_treatment_B['Q4_num_demo'].apply(regroup_education)

# Checking the distribution again
print("Education distribution for Treatment A:")
print(data_treatment_A['Education_Group'].value_counts())

print("\nEducation distribution for Treatment B:")
print(data_treatment_B['Education_Group'].value_counts())


Education distribution for Treatment A:
Advanced Education        19
Intermediate Education    14
Basic Education            7
Name: Education_Group, dtype: int64

Education distribution for Treatment B:
Advanced Education        20
Intermediate Education    14
Basic Education            5
Name: Education_Group, dtype: int64


In [49]:
# Conding the Anova test again this time for education levels
# ANOVA for Treatment A
fvalue_A, pvalue_A = stats.f_oneway(
    data_treatment_A['avg_usefulness_A'][data_treatment_A['Education_Group'] == 'Basic Education'],
    data_treatment_A['avg_usefulness_A'][data_treatment_A['Education_Group'] == 'Intermediate Education'],
    data_treatment_A['avg_usefulness_A'][data_treatment_A['Education_Group'] == 'Advanced Education']
)

# ANOVA for Treatment B
fvalue_B, pvalue_B = stats.f_oneway(
    data_treatment_B['avg_usefulness_B'][data_treatment_B['Education_Group'] == 'Basic Education'],
    data_treatment_B['avg_usefulness_B'][data_treatment_B['Education_Group'] == 'Intermediate Education'],
    data_treatment_B['avg_usefulness_B'][data_treatment_B['Education_Group'] == 'Advanced Education']
)

print(f"ANOVA result for Treatment A: F={fvalue_A}, p={pvalue_A}")
print(f"ANOVA result for Treatment B: F={fvalue_B}, p={pvalue_B}")

ANOVA result for Treatment A: F=2.2267734341997016, p=0.12213510865880371
ANOVA result for Treatment B: F=1.2086617784425198, p=0.3104253060983668


Given the data collected, education did not prove to have a significant impact on how useful participants found the personalized interface, for either treatment. 

## Influence of <b>Gender</b> on overall perceived usefulness

In [50]:
# Converting gender column to int

data_treatment_A['Q2_num_demo'] = data_treatment_A['Q2_num_demo'].astype(int)
data_treatment_B['Q2_num_demo'] = data_treatment_B['Q2_num_demo'].astype(int)

In [51]:
# Filter data for only male and female respondents
data_treatment_A_gender = data_treatment_A[data_treatment_A['Q2_num_demo'].isin([1, 2])]
data_treatment_B_gender = data_treatment_B[data_treatment_B['Q2_num_demo'].isin([1, 2])]

In [52]:
# Value counts for male and female respondents in Treatment A
gender_counts_A = data_treatment_A_gender['Q2_num_demo'].value_counts().sort_index()
print("Gender distribution for Treatment A:")
print(gender_counts_A)

# Value counts for male and female respondents in Treatment B
gender_counts_B = data_treatment_B_gender['Q2_num_demo'].value_counts().sort_index()
print("\nGender distribution for Treatment B:")
print(gender_counts_B)

Gender distribution for Treatment A:
1    26
2    13
Name: Q2_num_demo, dtype: int64

Gender distribution for Treatment B:
1    18
2    19
Name: Q2_num_demo, dtype: int64


In [53]:
# ANOVA for Treatment A
fvalue_A_gender, pvalue_A_gender = stats.f_oneway(
    data_treatment_A_gender['avg_usefulness_A'][data_treatment_A_gender['Q2_num_demo'] == 1],  # = Male Respondents
    data_treatment_A_gender['avg_usefulness_A'][data_treatment_A_gender['Q2_num_demo'] == 2]   # = Female Respondents 
)

# ANOVA for Treatment B
fvalue_B_gender, pvalue_B_gender = stats.f_oneway(
    data_treatment_B_gender['avg_usefulness_B'][data_treatment_B_gender['Q2_num_demo'] == 1],  # Male Repondents
    data_treatment_B_gender['avg_usefulness_B'][data_treatment_B_gender['Q2_num_demo'] == 2]   # = Female Respondents 
)

print(f"ANOVA result for Treatment A with gender: F={fvalue_A_gender}, p={pvalue_A_gender}")
print(f"ANOVA result for Treatment B with gender: F={fvalue_B_gender}, p={pvalue_B_gender}")

ANOVA result for Treatment A with gender: F=4.590220606578995, p=0.03880141836699093
ANOVA result for Treatment B with gender: F=0.4409463437922711, p=0.5110171220715675


### RESULT:
<b>For both treatments, there's no strong evidence (given p>0.05) to suggest that gender significantly influences the perceived usefulness of the personalized interface. This implies that the interface's effectiveness, in terms of perceived usefulness, is consistent across male and female respondents.

This is consistent with for example the findings of Kim and Choo (2013) who found that the correlations between experience, and likelihood of using kiosks at Quick Service Restaurants were generally not significantly moderated by gender generally not significantly moderated by gender
</b>



## 4. Hypotheses Analysis

## <b>H3a: Consumers that disclosed an inclination towards online personalization technologies will have a higher perceived usefulness of in-store personalized advertising interfaces.</b>

In [54]:
# Creating a new DataFrame for this analysis
analysis_df = merged_data[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen', 
                           'Q10A_num_use', 'Q11A_num_use', 'Q12A_num_use', 'Q13A_num_use', 'Q14A_num_use', 'Q15A_num_use',
                           'Q10B_num_use', 'Q11B_num_use', 'Q12B_num_use', 'Q13B_num_use', 'Q14B_num_use', 'Q15B_num_use']].copy()

In [55]:
# Ensuring the columns are numeric before calculating the mean
analysis_df[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']] = analysis_df[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']].apply(pd.to_numeric, errors='coerce')

In [56]:
# Now calculate the average positive experience
analysis_df['avg_positive_experience'] = analysis_df[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']].mean(axis=1)

In [57]:
# Defining the Columns for perceived usefulness for treatments A and B
usefulness_cols_A = ['Q10A_num_use', 'Q11A_num_use', 'Q12A_num_use', 'Q13A_num_use', 'Q14A_num_use', 'Q15A_num_use']
usefulness_cols_B = [col.replace('A', 'B') for col in usefulness_cols_A]

In [58]:
# Ensuring values and numeric
analysis_df[usefulness_cols_A] = analysis_df[usefulness_cols_A].apply(pd.to_numeric, errors='coerce')
analysis_df[usefulness_cols_B] = analysis_df[usefulness_cols_B].apply(pd.to_numeric, errors='coerce')

In [59]:
# Calculating average perceived usefulness for each respondent
analysis_df['avg_usefulness_A'] = analysis_df[usefulness_cols_A].mean(axis=1)
analysis_df['avg_usefulness_B'] = analysis_df[usefulness_cols_B].mean(axis=1)

In [60]:
# Caluclating Correlation
correlation_overall_A = analysis_df['avg_positive_experience'].corr(analysis_df['avg_usefulness_A'])
correlation_overall_B = analysis_df['avg_positive_experience'].corr(analysis_df['avg_usefulness_B'])

In [61]:
print(f"Correlation between positive experience and perceived usefulness in Treatment A: {correlation_overall_A}")
print(f"Correlation between positive experience and perceived usefulness in Treatment B: {correlation_overall_B}")

Correlation between positive experience and perceived usefulness in Treatment A: 0.5474344963164647
Correlation between positive experience and perceived usefulness in Treatment B: 0.5328930836971942


In [62]:
analysis_df

Q6_num_gen  Q7_num_gen  Q8_num_gen  Q9_num_gen  Q10A_num_use  \
0          NaN         NaN         NaN         NaN           NaN   
1          NaN         NaN         NaN         NaN           NaN   
2          5.0         5.0         4.0         5.0           NaN   
3          4.0         4.0         4.0         2.0           2.0   
4          5.0         5.0         5.0         1.0           1.0   
..         ...         ...         ...         ...           ...   
76         4.0         4.0         4.0         4.0           NaN   
77         4.0         4.0         5.0         4.0           5.0   
78         3.0         3.0         5.0         4.0           NaN   
79         5.0         5.0         5.0         5.0           6.0   
80         4.0         5.0         5.0         5.0           NaN   

    Q11A_num_use  Q12A_num_use  Q13A_num_use  Q14A_num_use  Q15A_num_use  \
0            NaN           NaN           NaN           NaN           NaN   
1            NaN           NaN           NaN           NaN           NaN   
2            NaN           NaN           NaN           NaN           NaN   
3            2.0           1.0           1.0           6.0           1.0   
4            1.0           1.0           1.0           1.0           1.0   
..           ...           ...           ...           ...           ...   
76           NaN           NaN           NaN           NaN           NaN   
77           5.0           6.0           6.0           7.0           6.0   
78           NaN           NaN           NaN           NaN           NaN   
79           5.0           6.0           6.0           7.0           6.0   
80           NaN           NaN           NaN           NaN           NaN   

    Q10B_num_use  Q11B_num_use  Q12B_num_use  Q13B_num_use  Q14B_num_use  \
0            NaN           NaN           NaN           NaN           NaN   
1            NaN           NaN           NaN           NaN           NaN   
2            5.0           7.0           5.0           4.0           6.0   
3            NaN           NaN           NaN           NaN           NaN   
4            NaN           NaN           NaN           NaN           NaN   
..           ...           ...           ...           ...           ...   
76           2.0           3.0           5.0           5.0           6.0   
77           NaN           NaN           NaN           NaN           NaN   
78           4.0           4.0           4.0           5.0           6.0   
79           NaN           NaN           NaN           NaN           NaN   
80           3.0           5.0           3.0           2.0           3.0   

    Q15B_num_use  avg_positive_experience  avg_usefulness_A  avg_usefulness_B  
0            NaN                      NaN               NaN               NaN  
1            NaN                      NaN               NaN               NaN  
2            5.0                     4.75               NaN          5.333333  
3            NaN                     3.50          2.166667               NaN  
4            NaN                     4.00          1.000000               NaN  
..           ...                      ...               ...               ...  
76           5.0                     4.00               NaN          4.333333  
77           NaN                     4.25          5.833333               NaN  
78           6.0                     3.75               NaN          4.833333  
79           NaN                     5.00          6.000000               NaN  
80           3.0                     4.75               NaN          3.166667  

[81 rows x 19 columns]

In [63]:
# Conducting a regression analysis
# Filter out NaN values for Treatment A
valid_A = analysis_df[['avg_positive_experience', 'avg_usefulness_A']].dropna()

# Regression for Treatment A
X_overall_A = sm.add_constant(valid_A['avg_positive_experience'])  # adding a constant
model_overall_A = sm.OLS(valid_A['avg_usefulness_A'], X_overall_A).fit()

# Filter out NaN values for Treatment B
valid_B = analysis_df[['avg_positive_experience', 'avg_usefulness_B']].dropna()

# Regression for Treatment B
X_overall_B = sm.add_constant(valid_B['avg_positive_experience'])  # adding a constant
model_overall_B = sm.OLS(valid_B['avg_usefulness_B'], X_overall_B).fit()

print(model_overall_A.summary())

                            OLS Regression Results                            
Dep. Variable:       avg_usefulness_A   R-squared:                       0.300
Model:                            OLS   Adj. R-squared:                  0.281
Method:                 Least Squares   F-statistic:                     16.26
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           0.000256
Time:                        19:45:14   Log-Likelihood:                -68.981
No. Observations:                  40   AIC:                             142.0
Df Residuals:                      38   BIC:                             145.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                     

In [64]:
print(model_overall_B.summary())

                            OLS Regression Results                            
Dep. Variable:       avg_usefulness_B   R-squared:                       0.284
Model:                            OLS   Adj. R-squared:                  0.265
Method:                 Least Squares   F-statistic:                     14.67
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           0.000478
Time:                        19:45:14   Log-Likelihood:                -68.028
No. Observations:                  39   AIC:                             140.1
Df Residuals:                      37   BIC:                             143.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                     

### Results for Treatment A:
To understand the relationship between consumers' positive experiences with personalization technologies and their perceived usefulness of in-store personalized advertising interfaces, a regression analysis was conducted. This analytical approach allowed us to quantify the strength and direction of the relationship between these variables.

Our findings indicate a significant association between positive experiences with personalization and perceived usefulness of the advertising interface. Specifically, for every unit increase in positive experience, the perceived usefulness score increases by approximately 0.92 units. This relationship explained about 30% of the variance in perceived usefulness, denoted by an R-squared value of 0.300, signifying a moderate and meaningful association.

While the intercept of the model, which represents the baseline perceived usefulness in the absence of positive experiences, was found to be 1.0844, it wasn't statistically different from zero. However, the overall model was statistically significant, with a Prob (F-statistic) value of 0.000256, underscoring the importance of positive experiences as a predictor.

In conclusion, for participants in Treatment A, their prior positive experiences with personalization technologies significantly influence their perceptions of the usefulness of new personalized advertising interfaces.

### Results for Treatment B:
Again, to understand the influence of consumers' positive experiences with personalization technologies on their perceived usefulness of in-store personalized advertising interfaces, the same method of a regression analysis for Treatment B was applied. This method was chosen to quantify the strength and directionality of the relationship between these two variables.

Our analysis revealed a notable association. Specifically, a unit increase in positive experience corresponded to an approximate 1.02 unit rise in perceived usefulness. This relationship accounted for about 28.4% of the variance in perceived usefulness, as indicated by the R-squared value. This moderate association underscores the importance of prior positive experiences in shaping perceptions of new personalized interfaces.

While the model's intercept, suggesting the baseline perceived usefulness without any positive experiences, was 0.2219, it wasn't statistically distinguishable from zero. However, the overall model's significance, with a Prob (F-statistic) value of 0.000478, emphasizes the predictive power of positive experiences.

To sum up, for those in Treatment B, prior positive experiences with personalization technologies significantly shaped their perceptions of the usefulness of new personalized advertising interfaces, mirroring the findings from Treatment A.



## <b>H1: Consumers exposed to the QR code scanner (representing implicit data collection) will perceive higher usefulness compared to those exposed to the biometric scanning camera (representing explicit data collection).
(I.e. respondents presented to treatment A)</b>

In [65]:
# Calculate average perceived usefulness for each respondent in both treatments
analysis_df['avg_usefulness_A'] = analysis_df[usefulness_cols_A].mean(axis=1)
analysis_df['avg_usefulness_B'] = analysis_df[usefulness_cols_B].mean(axis=1)

# Drop NaN values for Treatment A and B
avg_usefulness_A_clean = analysis_df['avg_usefulness_A'].dropna()
avg_usefulness_B_clean = analysis_df['avg_usefulness_B'].dropna()

In [66]:
# Conduct an independent samples t-test using Welch's t-test
t_stat, p_value = stats.ttest_ind(avg_usefulness_A_clean, avg_usefulness_B_clean, equal_var=False)

In [67]:
print(f"t-statistic: {t_stat}")
print(f"p-value: {p_value}")

t-statistic: 0.5169690886668384
p-value: 0.6066613088177961


In [68]:
# Interpret the results
if p_value < 0.05:
    print("The difference in perceived usefulness between the two treatments is statistically significant.")
else:
    print("The difference in perceived usefulness between the two treatments is not statistically significant.")

The difference in perceived usefulness between the two treatments is not statistically significant.


### Results:
In order to investigate the perceived usefulness of two different personalized advertising interfaces, an independent samples t-test was conducted. The two interfaces in question were the QR code scanner (representing implicit data collection) presented to respondents in treatment A, and the biometric scanning camera (representing explicit data collection) presented in the treatment B.

The results of the t-test revealed that there was no statistically significant difference in the perceived usefulness between the two treatments, t(77) = 0.517, p = 0.607. This suggests that, based on the data collected, consumers did not perceive one interface as more useful than the other, regardless of the data collection method being implicit or explicit.

## <b>H3: Consumers that disclosed an inclination towards online personalization technologies will have a higher perceived usefulness of in-store personalized advertising interfaces.</b>

In [69]:
# Creating a dummy variable for the treatment
analysis_df['treatment_dummy'] = 0  # Default to 0 for QR code scanner
analysis_df.loc[analysis_df['avg_usefulness_B'].notna(), 'treatment_dummy'] = 1  # Set to 1 for biometric scanning camera

In [70]:
# Creating a dummy variable for the treatment
analysis_df['treatment_dummy'] = 0  # Default to 0 for QR code scanner (Treatment A)
analysis_df.loc[analysis_df['avg_usefulness_B'].notna(), 'treatment_dummy'] = 1  # Set to 1 for biometric scanning camera (Treatment B)

In [71]:
# Creating interaction term
analysis_df['interaction'] = analysis_df['avg_positive_experience'] * analysis_df['treatment_dummy']


In [72]:
# Creating interaction term# Set up the regression model
X = analysis_df[['avg_positive_experience', 'treatment_dummy', 'interaction']]
X = sm.add_constant(X)  # adding a constant
y = analysis_df[['avg_usefulness_A', 'avg_usefulness_B']].mean(axis=1)
analysis_df['interaction'] = analysis_df['avg_positive_experience'] * analysis_df['treatment_dummy']


In [73]:
# Printing the model
model = sm.OLS(y, X, missing='drop').fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                  0.266
Method:                 Least Squares   F-statistic:                     10.43
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           8.21e-06
Time:                        19:45:14   Log-Likelihood:                -137.02
No. Observations:                  79   AIC:                             282.0
Df Residuals:                      75   BIC:                             291.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                     

### Results:
In the investigation of the influence of consumers' stance towards personalization on their perceived usefulness of two different data collection methods (QR code scanner as an implicit method and biometric scanning camera as an explicit method), we employed a regression analysis. The analysis was structured to understand not only the individual effects of general stance towards personalization and treatment type but also their interaction.

The regression model explained approximately 29.4% of the variance in perceived usefulness (R-squared = 0.294). The stance towards personalization was found to be a significant predictor of perceived usefulness (β = 0.9203, p < 0.001). This suggests that, on average, for every unit increase in positive stance towards personalization, there's an associated increase of 0.9203 units in the perceived usefulness of the personalized advertising interface, regardless of the treatment type.

However, when examining the treatment type (QR code scanner vs. biometric scanning camera), the coefficient was not statistically significant (β = -0.8625, p = 0.522). This indicates that, on its own, the type of data collection method (implicit vs. explicit) did not significantly influence the perceived usefulness.

Most crucially, the interaction term between the stance towards personalization and the treatment type was also not statistically significant (β = 0.1003, p = 0.775). This suggests that the relationship between stance towards personalization and perceived usefulness does not differ based on whether the consumer was exposed to the QR code scanner or the biometric scanning camera.

In conclusion, while individuals' positive stance towards personalization technologies significantly influences their perceived usefulness of in-store personalized advertising interfaces, the method of data collection (implicit vs. explicit) does not seem to moderate this relationship.

## <b>H2a: Consumers exposed to the biometric scanning camera (explicit data collection) will exhibit higher privacy concerns than those exposed to the QR code scanner (implicit data collection).</b>

In [74]:
# Extracting relevant columns for privacy concerns
privacy_cols_A = ['Q16A_num_priv', 'Q17A_num_priv', 'Q18A_num_priv', 'Q19A_num_priv', 'Q20A_num_priv']
privacy_cols_B = [col.replace('A', 'B') for col in privacy_cols_A]

In [75]:
# Transform data to numeric
data_treatment_A[privacy_cols_A] = data_treatment_A[privacy_cols_A].apply(pd.to_numeric, errors='coerce')
data_treatment_B[privacy_cols_B] = data_treatment_B[privacy_cols_B].apply(pd.to_numeric, errors='coerce')

In [76]:
# Calculate average privacy concern for each respondent
data_treatment_A['avg_privacy_concern_A'] = data_treatment_A[privacy_cols_A].mean(axis=1)
data_treatment_B['avg_privacy_concern_B'] = data_treatment_B[privacy_cols_B].mean(axis=1)

In [77]:
from scipy.stats import levene

# Levene's test for equality of variances
stat, p_val_levene = levene(data_treatment_A['avg_privacy_concern_A'].dropna(), 
                            data_treatment_B['avg_privacy_concern_B'].dropna())

print(f"Levene's test p-value: {p_val_levene}")

Levene's test p-value: 0.7063891815910315


In [78]:
from scipy.stats import ttest_ind

In [79]:
# Conducting the appropriate t-test
if p_val_levene > 0.05:
    # If p-value is greater than 0.05, variances can be assumed to be equal
    t_stat, p_val = ttest_ind(data_treatment_A['avg_privacy_concern_A'].dropna(), 
                              data_treatment_B['avg_privacy_concern_B'].dropna(), 
                              equal_var=True)
else:
    # If p-value is less than 0.05, use Welch's t-test (equal_var=False)
    t_stat, p_val = ttest_ind(data_treatment_A['avg_privacy_concern_A'].dropna(), 
                              data_treatment_B['avg_privacy_concern_B'].dropna(), 
                              equal_var=False)

print(f"\nt-statistic: {t_stat}")
print(f"p-value: {p_val}")


t-statistic: -1.2405528966382828
p-value: 0.2185376687608684


### Results:
In examining the potential difference in privacy concerns between consumers exposed to the biometric scanning camera (explicit data collection) and those exposed to the QR code scanner (implicit data collection), we first tested the assumption of homogeneity of variances using Levene's test. The result of Levene's test (p = 0.706) indicated that the variances of privacy concerns between the two groups were not significantly different, allowing us to proceed with the assumption of equal variances.

Subsequently, an independent samples t-test was conducted to compare the average privacy concerns between the two treatments. The results revealed no statistically significant difference in privacy concerns between consumers exposed to the biometric scanning camera and those exposed to the QR code scanner, t(78) = -1.2405, p = 0.2185.

In conclusion, our findings do not support the hypothesis H2a. The type of data collection method, whether explicit (biometric scanning camera) or implicit (QR code scanner), did not significantly influence consumers' privacy concerns in this study.

## <b>H2b: Consumers exhibiting higher levels of privacy concern will perceive lower levels of usefulness of PPA</b>

In [80]:
# Calculate average privacy concern for each respondent in both treatments
data_treatment_A['avg_privacy_concern'] = data_treatment_A[privacy_cols_A].mean(axis=1)
data_treatment_B['avg_privacy_concern'] = data_treatment_B[privacy_cols_B].mean(axis=1)

# Calculate average usefulness for each respondent in both treatments
data_treatment_A['avg_usefulness'] = data_treatment_A[usefulness_cols_A].mean(axis=1)
data_treatment_B['avg_usefulness'] = data_treatment_B[usefulness_cols_B].mean(axis=1)

In [81]:
# Combine the two dataframes for the regression analysis
combined_data = pd.concat([data_treatment_A, data_treatment_B], ignore_index=True)
combined_data

ResponseId Q1_text_demo  Q1_num_demo               Q2_text_demo  \
0   R_2P50BFiax5qSAly      25 - 34            3                       Male   
1   R_10BgiVtu9sGveBS      25 - 34            3                       Male   
2   R_0IzxnJkKlYsL2CZ      45 - 54            5                     Female   
3   R_12JQ6Oqs8oVy8N4      25 - 34            3                     Female   
4   R_UDsvun7YJiU8XOV      25 - 34            3                     Female   
..                ...          ...          ...                        ...   
74  R_3e5jukLQ56gnHA7     Under 18            1  Non-binary / third gender   
75  R_yO5192peQcNQWzL      18 - 24            2                     Female   
76  R_2vdjdFUkYWwdOki      25 - 34            3                       Male   
77  R_BriPmN2wELRwAet      45 - 54            5                     Female   
78  R_2VyE3lVoeS8d6yE      18 - 24            2                       Male   

    Q2_num_demo              Q3_text_demo  Q3_num_demo  \
0             1                  Slovakia          157   
1             1                     Niger          125   
2             2  United States of America          187   
3             2                  Slovakia          157   
4             2                  Slovakia          157   
..          ...                       ...          ...   
74            3                  Slovakia          157   
75            2                     China           36   
76            1                  Slovakia          157   
77            2                  Slovakia          157   
78            1                  Slovakia          157   

                        Q4_text_demo  Q4_num_demo          Q5_text_gen  \
0     Master's degree (e.g. MA, MSc)            5    Slightly familiar   
1              Less than high school            1   Extremely familiar   
2     Master's degree (e.g. MA, MSc)            5  Moderately familiar   
3     Master's degree (e.g. MA, MSc)            5    Slightly familiar   
4   Bachelor's degree (e.g. BA, BSc)            4  Moderately familiar   
..                               ...          ...                  ...   
74             Less than high school            1    Slightly familiar   
75  Bachelor's degree (e.g. BA, BSc)            4    Slightly familiar   
76  Bachelor's degree (e.g. BA, BSc)            4  Moderately familiar   
77    Master's degree (e.g. MA, MSc)            5  Moderately familiar   
78  Bachelor's degree (e.g. BA, BSc)            4        Very familiar   

    Q5_num_gen                 Q6_text_gen  Q6_num_gen  \
0            2              Somewhat agree           4   
1            5              Strongly agree           5   
2            3              Somewhat agree           4   
3            2              Somewhat agree           4   
4            3           Strongly disagree           1   
..         ...                         ...         ...   
74           2           Somewhat disagree           2   
75           2  Neither agree nor disagree           3   
76           3              Somewhat agree           4   
77           3  Neither agree nor disagree           3   
78           4              Somewhat agree           4   

                   Q7_text_gen  Q7_num_gen                 Q8_text_gen  \
0               Somewhat agree           4              Somewhat agree   
1               Strongly agree           5              Strongly agree   
2   Neither agree nor disagree           3              Strongly agree   
3               Somewhat agree           4              Strongly agree   
4            Strongly disagree           1           Somewhat disagree   
..                         ...         ...                         ...   
74              Somewhat agree           4  Neither agree nor disagree   
75              Somewhat agree           4              Somewhat agree   
76              Somewhat agree           4              Somewhat agree   
77  Neither agree nor disagree           3         

In [82]:
# Conducting a regression analysis
X = sm.add_constant(combined_data['avg_privacy_concern'])  # adding a constant
model = sm.OLS(combined_data['avg_usefulness'], X).fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:         avg_usefulness   R-squared:                       0.039
Model:                            OLS   Adj. R-squared:                  0.026
Method:                 Least Squares   F-statistic:                     3.090
Date:                Mon, 02 Oct 2023   Prob (F-statistic):             0.0827
Time:                        19:45:14   Log-Likelihood:                -149.23
No. Observations:                  79   AIC:                             302.5
Df Residuals:                      77   BIC:                             307.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                   5.5142    

### <b>Result:</b>
In our exploration of Hypothesis 2b, we sought to understand the potential relationship between consumers' privacy concerns and their perceived usefulness of personalized public advertising (PPA). Utilizing a regression analysis, we positioned the average privacy concern as the predictor and the average perceived usefulness of PPA as the outcome.

The regression coefficient for average privacy concern stood at -0.3259. This negative value indicates a decline in the perceived usefulness of PPA for every unit increase in privacy concerns. Specifically, for every one-point rise in the privacy concern score, there's an associated decrease of approximately 0.326 in the perceived usefulness score, all else being constant.

However, the statistical significance of this relationship, as indicated by a p-value of 0.083, is marginal. While this exceeds the conventional 0.05 threshold for statistical significance, the proximity suggests a potential trend worth noting.

The model's R-squared value of 0.039 further reveals that privacy concerns account for roughly 3.9% of the variance in perceived usefulness. This suggests that while there's some influence of privacy concerns on perceived usefulness, other external factors not captured in this model might also play a substantial role.

In conclusion, these findings provide tentative evidence pointing towards a negative relationship between privacy concerns and the perceived usefulness of PPA. However, the relationship isn't robustly significant in the current dataset. Given the near-significant p-value, further investigations with perhaps larger sample sizes or varied conditions might offer more definitive insights.

## <b>H4: Respondents who have expressed an inclination towards personalization technologies online will disclose more types of personal data.</b>

In [83]:
# Transforming data into a list of integers from it's string type
data_treatment_A['Q21A_data_list'] = data_treatment_A['Q21A_num_data'].str.split(',').apply(lambda x: [int(i) for i in x if i.isdigit()])
data_treatment_B['Q21B_data_list'] = data_treatment_B['Q21B_num_data'].str.split(',').apply(lambda x: [int(i) for i in x if i.isdigit()])

In [84]:
# Calculating the average positive experience in each treatment
data_treatment_A['avg_positive_experience'] = data_treatment_A[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']].mean(axis=1)
data_treatment_B['avg_positive_experience'] = data_treatment_B[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']].mean(axis=1)

In [85]:
# Calculating the number of data types people were willing to disclose
data_treatment_A['num_data_types_A'] = data_treatment_A['Q21A_data_list'].apply(len)
data_treatment_B['num_data_types_B'] = data_treatment_B['Q21B_data_list'].apply(len)

In [86]:
# Regression for Treatment A
X_A = sm.add_constant(data_treatment_A['avg_positive_experience'])  # adding a constant
y_A = data_treatment_A['num_data_types_A']
model_A = sm.OLS(y_A, X_A).fit()

In [87]:
# Print out the regression summaries
print("Regression Results for Treatment A:")
print(model_A.summary())

Regression Results for Treatment A:
                            OLS Regression Results                            
Dep. Variable:       num_data_types_A   R-squared:                       0.254
Model:                            OLS   Adj. R-squared:                  0.234
Method:                 Least Squares   F-statistic:                     12.95
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           0.000912
Time:                        19:45:14   Log-Likelihood:                -65.227
No. Observations:                  40   AIC:                             134.5
Df Residuals:                      38   BIC:                             137.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------

In [88]:
# Regression for Treatment B
X_B = sm.add_constant(data_treatment_B['avg_positive_experience'])  # adding a constant
y_B = data_treatment_B['num_data_types_B']
model_B = sm.OLS(y_B, X_B).fit()

In [89]:
print("\nRegression Results for Treatment B:")
print(model_B.summary())


Regression Results for Treatment B:
                            OLS Regression Results                            
Dep. Variable:       num_data_types_B   R-squared:                       0.250
Model:                            OLS   Adj. R-squared:                  0.230
Method:                 Least Squares   F-statistic:                     12.35
Date:                Mon, 02 Oct 2023   Prob (F-statistic):            0.00118
Time:                        19:45:14   Log-Likelihood:                -66.950
No. Observations:                  39   AIC:                             137.9
Df Residuals:                      37   BIC:                             141.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------

### Results:
In Treatment A, we sought to understand the relationship between respondents' positive inclination towards personalization and their willingness to disclose various types of personal data. The regression analysis yielded an R-squared value of 0.254, suggesting that approximately 25.4% of the variance in the willingness to disclose data can be explained by the positive experience with personalization technologies.

The coefficient for avg_positive_experience is 0.7476. This indicates that for every one-unit increase in the positive experience score, the number of data types respondents are willing to disclose increases by approximately 0.75, holding all else constant. This relationship is statistically significant, with a p-value less than 0.05 (p=0.001), reinforcing the idea that those with a more positive stance towards personalization are more open to sharing a broader range of personal data.

The intercept (constant) is 0.3007, representing the estimated number of data types respondents are willing to disclose when the positive experience score is zero. However, this value is not statistically significant (p=0.696), suggesting that it doesn't differ meaningfully from zero.

In conclusion, for Treatment A, there is a significant positive relationship between the positive experience with personalization technologies and the willingness to disclose multiple types of personal data. This suggests that fostering positive experiences with personalization can potentially lead to greater openness in data sharing among consumers.

For Treatment B, the regression analysis produced an R-squared value of 0.250, indicating that about 25% of the variability in the willingness to disclose data is accounted for by the positive experience with personalization technologies.

The coefficient for avg_positive_experience stands at 0.9109. This suggests that for every unit increase in the positive experience score, there's an associated increase of approximately 0.91 in the number of data types respondents are inclined to share, all other factors being constant. This relationship is statistically significant with a p-value less than 0.05 (p=0.001), emphasizing that individuals with a more favorable view of personalization are more amenable to sharing a wider array of personal data.

The intercept, or constant, is -0.3043, which denotes the estimated number of data types respondents would be willing to disclose when their positive experience score is zero. However, this value isn't statistically significant (p=0.768), implying that it doesn't deviate significantly from zero.

In summation, for Treatment B, there exists a notable positive correlation between the positive experiences with personalization technologies and the willingness to disclose multiple types of personal data. This underscores the notion that positive personalization experiences can enhance consumers' willingness to share more personal information.

## <b>H5a: Respondents who demonstrate higher levels of perceived usefulness for either of the data collection interfaces (QR code scanner or biometric camera) will be more inclined to disclose more types of personal data.</b>

In [90]:
# Regression for Treatment A
X_A = sm.add_constant(data_treatment_A['avg_usefulness_A'])  # adding a constant
model_A = sm.OLS(data_treatment_A['num_data_types_A'], X_A).fit()

print(model_A.summary())

                            OLS Regression Results                            
Dep. Variable:       num_data_types_A   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                  0.246
Method:                 Least Squares   F-statistic:                     13.75
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           0.000664
Time:                        19:45:15   Log-Likelihood:                -64.912
No. Observations:                  40   AIC:                             133.8
Df Residuals:                      38   BIC:                             137.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.9738      0.569  

In [91]:
# Regression for Treatment B
X_B = sm.add_constant(data_treatment_B['avg_usefulness_B'])  # adding a constant
model_B = sm.OLS(data_treatment_B['num_data_types_B'], X_B).fit()

print(model_B.summary())

                            OLS Regression Results                            
Dep. Variable:       num_data_types_B   R-squared:                       0.165
Model:                            OLS   Adj. R-squared:                  0.142
Method:                 Least Squares   F-statistic:                     7.290
Date:                Mon, 02 Oct 2023   Prob (F-statistic):             0.0104
Time:                        19:45:15   Log-Likelihood:                -69.061
No. Observations:                  39   AIC:                             142.1
Df Residuals:                      37   BIC:                             145.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                1.6031      0.638  

### <b>Results:</b>
In Treatment A, we investigated the relationship between the perceived usefulness of the QR code scanner interface (avg_usefulness_A) and the willingness of respondents to disclose various types of personal data (num_data_types_A).

The regression analysis yielded an R-squared value of 0.266, suggesting that approximately 26.6% of the variance in the willingness to disclose personal data can be explained by the perceived usefulness of the QR code scanner interface. This indicates a moderate relationship between the two variables.

The coefficient for avg_usefulness_A is 0.4547, implying that for every one-unit increase in the perceived usefulness score, respondents are willing to disclose approximately 0.45 more types of personal data. This relationship is statistically significant with a p-value less than 0.05 (p=0.001).

The intercept (constant) is 0.9738, representing the estimated number of data types respondents are willing to disclose when the perceived usefulness score is zero. This value is marginally significant with a p-value of 0.095.

In conclusion, for Treatment A, there's a positive and statistically significant relationship between the perceived usefulness of the QR code scanner interface and the willingness of respondents to disclose more types of personal data. The results suggest that as respondents find the interface more useful, they are more inclined to share a broader range of personal information.

For Treatment B, The regression analysis produced an R-squared value of 0.165, indicating that about 16.5% of the variance in the willingness to disclose personal data is accounted for by the perceived usefulness of the biometric scanning camera interface. This suggests a modest relationship between these two variables.

The coefficient for avg_usefulness_B stands at 0.3857. This implies that for every unit increase in the perceived usefulness score, respondents are inclined to disclose approximately 0.39 more types of personal data. This relationship is statistically significant, as evidenced by a p-value less than 0.05 (p=0.010).

The intercept (constant) is valued at 1.6031, which represents the estimated number of data types respondents are willing to disclose when the perceived usefulness score is zero. This value is statistically significant with a p-value of 0.016.

To sum up, for Treatment B, again, there exists a positive and statistically significant relationship between the perceived usefulness of the biometric scanning camera interface and the willingness of respondents to disclose a wider array of personal data. The findings suggest that as respondents perceive the interface as more useful, they are more open to sharing diverse personal information.

## <b>H5b: Respondents who demonstrate higher levels of privacy concern for either of the data collection interfaces (QR code scanner or biometric camera) will be willing to disclose less types of personal data.</b>

In [92]:
# Setting option 8 "None of the above" as 0 For Treatment A
data_treatment_A['unwilling_to_disclose_A'] = data_treatment_A['Q21A_num_data'].apply(lambda x: 1 if '8' in str(x).split(',') else 0)
data_treatment_A.loc[data_treatment_A['unwilling_to_disclose_A'] == 1, 'num_data_types_A'] = 0

In [93]:
# Setting option 8 "None of the above" as 0 For Treatment B
data_treatment_B['unwilling_to_disclose_B'] = data_treatment_B['Q21B_num_data'].apply(lambda x: 1 if '8' in str(x).split(',') else 0)
data_treatment_B.loc[data_treatment_B['unwilling_to_disclose_B'] == 1, 'num_data_types_B'] = 0

In [94]:
# Regression for Treatment A
X_A = sm.add_constant(data_treatment_A['avg_privacy_concern_A'])
y_A = data_treatment_A['num_data_types_A']
model_A = sm.OLS(y_A, X_A).fit()

In [95]:
print("Results for Treatment A:\n", model_A.summary())

Results for Treatment A:
                             OLS Regression Results                            
Dep. Variable:       num_data_types_A   R-squared:                       0.200
Model:                            OLS   Adj. R-squared:                  0.179
Method:                 Least Squares   F-statistic:                     9.527
Date:                Mon, 02 Oct 2023   Prob (F-statistic):            0.00377
Time:                        19:45:15   Log-Likelihood:                -69.871
No. Observations:                  40   AIC:                             143.7
Df Residuals:                      38   BIC:                             147.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
cons

In [96]:
# Regression for Treatment B
X_B = sm.add_constant(data_treatment_B['avg_privacy_concern_B'])
y_B = data_treatment_B['num_data_types_B']
model_B = sm.OLS(y_B, X_B).fit()

In [97]:
print("\nResults for Treatment B:\n", model_B.summary())


Results for Treatment B:
                             OLS Regression Results                            
Dep. Variable:       num_data_types_B   R-squared:                       0.174
Model:                            OLS   Adj. R-squared:                  0.152
Method:                 Least Squares   F-statistic:                     7.791
Date:                Mon, 02 Oct 2023   Prob (F-statistic):            0.00826
Time:                        19:45:15   Log-Likelihood:                -74.464
No. Observations:                  39   AIC:                             152.9
Df Residuals:                      37   BIC:                             156.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
con

### <b>Results:</b>
In the analysis for Treatment A, we examined the relationship between respondents' average privacy concerns (avg_privacy_concern_A) and their willingness to disclose different types of personal data (num_data_types_A). The regression model accounted for the "None of the above" option, which indicates an unwillingness to disclose any data type.

The R-squared value of the model is 0.200, suggesting that approximately 20% of the variance in the number of data types respondents are willing to disclose can be explained by their average privacy concerns.

The coefficient for avg_privacy_concern_A is -0.7129, indicating a negative relationship between privacy concerns and willingness to disclose data. Specifically, for every one-unit increase in privacy concern, the number of data types a respondent is willing to disclose decreases by approximately 0.71, holding all else constant. This relationship is statistically significant with a p-value of 0.004, which is less than the 0.05 threshold.

The constant (or intercept) of the model is 5.5411. This can be interpreted as the average number of data types a respondent is willing to disclose when their privacy concern is zero. However, in practical terms, a privacy concern score of zero may not be meaningful, so the primary focus should be on the coefficient of the privacy concern variable.

In conclusion, for Treatment A, there is a significant negative relationship between the level of privacy concern and the willingness to disclose personal data types. As respondents' privacy concerns increase, their inclination to share personal data types decreases. This finding aligns with the intuitive understanding that individuals with higher privacy concerns would be more reserved in sharing their personal information.

For Treatment B, the model's R-squared value stands at 0.174, indicating that around 17.4% of the variance in the number of data types respondents are willing to disclose can be attributed to their average privacy concerns.

The coefficient for avg_privacy_concern_B is -0.7703. This negative coefficient suggests that as privacy concerns rise, the number of data types respondents are willing to disclose decreases. Specifically, for every unit increase in privacy concern, the number of data types a respondent is willing to disclose diminishes by approximately 0.77, all else being equal. This relationship is statistically significant, as evidenced by a p-value of 0.008, which is below the conventional 0.05 threshold.

The model's constant (or intercept) is 6.1442. This value represents the average number of data types a respondent would be willing to disclose if they had no privacy concerns. However, as with Treatment A, a privacy concern score of zero might not be practically meaningful, so the emphasis should be placed on the coefficient of the privacy concern variable.

In summary, for Treatment B, there was also recorded a significant inverse relationship between the degree of privacy concern and the willingness to disclose personal data types. As respondents' privacy concerns intensify, their propensity to share personal data types diminishes. This outcome is consistent with the notion that individuals with heightened privacy concerns would be more cautious about sharing their personal details.

## <b>H6a:Consumers with heightened privacy concerns related to personalization will have a stronger expectation of receiving more substantial rewards in exchange for their engagement in personalization.</b> 

In [98]:
# Transforming the expected rewards data For Treatment A
data_treatment_A['num_rewards_A'] = data_treatment_A['Q22A_num_rew'].str.split(',').apply(lambda x: 0 if '6' in x else len(x))

# Transforming the expected rewards data For Treatment B
data_treatment_B['num_rewards_B'] = data_treatment_B['Q22B_num_rew'].str.split(',').apply(lambda x: 0 if '6' in x else len(x))

In [99]:
data_treatment_A

ResponseId Q1_text_demo  Q1_num_demo               Q2_text_demo  \
3   R_2P50BFiax5qSAly      25 - 34            3                       Male   
4   R_10BgiVtu9sGveBS      25 - 34            3                       Male   
6   R_0IzxnJkKlYsL2CZ      45 - 54            5                     Female   
7   R_12JQ6Oqs8oVy8N4      25 - 34            3                     Female   
10  R_UDsvun7YJiU8XOV      25 - 34            3                     Female   
12  R_1hW7217wTXnbVis      18 - 24            2                       Male   
14  R_2b3OIsBI74Whfge      25 - 34            3                       Male   
16  R_VPzqRUghYEmK5ZT      18 - 24            2                     Female   
17  R_dj9dwHCFFUViAlr      18 - 24            2                       Male   
20  R_26hEULOxCNIq4Uq      25 - 34            3                       Male   
21  R_33jQFD4heG49nhT      25 - 34            3                       Male   
23  R_3D8iJocCDWaeHbN      25 - 34            3                       Male   
25  R_2YlIv6zvkama7ok      25 - 34            3                       Male   
27  R_1reLjdajejJYdxz      25 - 34            3                       Male   
30  R_3JDaR8Ls0g0Lp9d      25 - 34            3                       Male   
32  R_3My6OJ6O7Qi9K5g      25 - 34            3                       Male   
33  R_1H0jRe0hDL6LHuN      18 - 24            2                       Male   
36  R_2bKk3ZRZ2aeqFW2      25 - 34            3                       Male   
37  R_1hGshFyOfOoMNF5      25 - 34            3                       Male   
38  R_2S79sBeDxo7ixb6      25 - 34            3                       Male   
41  R_3kMwOMXnu5tmcHK      45 - 54            5                     Female   
42  R_24uPqIi4Yt0i8hx      25 - 34            3                       Male   
44  R_1jg50KblYmUiWSE      25 - 34            3                     Female   
46  R_e5peeuWARDPljGx      18 - 24            2                     Female   
48  R_28S9XuURSf44q5f      25 - 34            3                       Male   
49  R_DnMWPMMbvVgqeZP      18 - 24            2                       Male   
51  R_2UbbhlEufRVPASR      18 - 24            2                       Male   
55  R_31NvIW4IzKAZdoW      55 - 64            6                     Female   
58  R_d6eL3OQ0Zp8cf4d      25 - 34            3                     Female   
59  R_3PXFKAnFNHSt3Lv      18 - 24            2                       Male   
62  R_3O99kaOnQmbWnbO      35 - 44            4                       Male   
65  R_umj5cpCMR8WfYlj      18 - 24            2                     Female   
66  R_2QDqZOHabnMXUpc      18 - 24            2                       Male   
68  R_3KDRnZnhu6MLNw8      25 - 34            3  Non-binary / third gender   
69  R_30kpEdGqF0NKfq5      18 - 24            2                       Male   
72  R_3M58P8By9n6F4l0      45 - 54            5                       Male   
73  R_3O6MzEaIXXX2eZs      25 - 34            3                     Female   
75  R_3G8je3roSrJRCs7      18 - 24            2                     Female   
77  R_BPq1Lvk0HUzl3tD      18 - 24            2                     Female   
79  R_2dsdedJjCrVL8ew      25 - 34            3                       Male   

    Q2_num_demo              Q3_text_demo  Q3_num_demo  \
3             1                  Slovakia          157   
4             1                     Niger          125   
6             2  United States of America          187   
7             2                  Slovakia          157   
10            2                  Slovakia          157   
12            1                  Slovakia          157   
14            1                   Germany           65   
16            2                    Norway          128   
17            1                   Hungary           76   
20            1                  Slovakia          157   
21            1                  Slovakia          157   
23            1                  Slovakia          157   
25            1                  Slovakia          157   


In [100]:
# For Treatment A
X_A = data_treatment_A['avg_privacy_concern_A']
X_A = sm.add_constant(X_A)  # Adds a constant term to the predictor
y_A = data_treatment_A['num_rewards_A']

model_A = sm.OLS(y_A, X_A).fit()

In [101]:
print("Results for Treatment A:\n", model_A.summary())

Results for Treatment A:
                             OLS Regression Results                            
Dep. Variable:          num_rewards_A   R-squared:                       0.114
Model:                            OLS   Adj. R-squared:                  0.091
Method:                 Least Squares   F-statistic:                     4.896
Date:                Mon, 02 Oct 2023   Prob (F-statistic):             0.0330
Time:                        19:45:15   Log-Likelihood:                -68.684
No. Observations:                  40   AIC:                             141.4
Df Residuals:                      38   BIC:                             144.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
cons

In [102]:
# For Treatment B
X_B = data_treatment_B['avg_privacy_concern_B']
X_B = sm.add_constant(X_B)  # Adds a constant term to the predictor
y_B = data_treatment_B['num_rewards_B']

model_B = sm.OLS(y_B, X_B).fit()

In [103]:
print("\nResults for Treatment B:\n", model_B.summary())


Results for Treatment B:
                             OLS Regression Results                            
Dep. Variable:          num_rewards_B   R-squared:                       0.034
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     1.285
Date:                Mon, 02 Oct 2023   Prob (F-statistic):              0.264
Time:                        19:45:15   Log-Likelihood:                -71.190
No. Observations:                  39   AIC:                             146.4
Df Residuals:                      37   BIC:                             149.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
con

### <b>Results:</b>
In examining the relationship between privacy concerns and the expectation of rewards for data disclosure, distinct patterns emerge for the two treatments.


For respondents under Treatment A (QR code scanner), there's a negative relationship between the level of privacy concerns and the number of rewards they expect in return for their data. Specifically, for every unit increase in privacy concern, there's an approximate decrease of 0.496 in the number of rewards expected. This relationship is statistically significant at the 5% level (p=0.033). The model explains about 11.4% of the variance in the number of rewards expected (R-squared = 0.114). This suggests that as privacy concerns rise, respondents in Treatment A expect fewer rewards in return for their data.

For Treatment B (bioscanning camera), the relationship between privacy concerns and expected rewards is also negative, but it's weaker and not statistically significant (p=0.264). The coefficient of -0.2876 suggests that for every unit increase in privacy concern, there's a decrease of approximately 0.288 in the number of rewards expected. However, given the lack of statistical significance, we cannot confidently assert this relationship for the population. The model's R-squared value of 0.034 indicates that it explains only about 3.4% of the variance in the number of rewards expected.

Conclusion:
The findings suggest that for Treatment A, heightened privacy concerns correlate with reduced expectations for rewards. This could imply that when individuals are more concerned about their privacy, they might be less enticed by rewards or perhaps believe that no amount of rewards can compensate for potential privacy breaches. However, this relationship is not as clear for Treatment B, indicating that the context or nature of the treatment might play a role in shaping these perceptions. Further research might be needed to delve deeper into the nuances of these findings.

## TESTING FURTHER (IGNORE)

In [104]:


# Combine the num_rewards columns
data_treatment_A['num_rewards'] = data_treatment_A['num_rewards_A']
data_treatment_B['num_rewards'] = data_treatment_B['num_rewards_B']

# Combine the avg_privacy_concern columns
data_treatment_A['avg_privacy_concern'] = data_treatment_A['avg_privacy_concern_A']
data_treatment_B['avg_privacy_concern'] = data_treatment_B['avg_privacy_concern_B']

# Combine the two datasets
combined_data = pd.concat([data_treatment_A, data_treatment_B], ignore_index=True)

# Creating a dummy variable for the treatment type
combined_data['treatment_B_dummy'] = 0
combined_data.loc[combined_data.index.isin(data_treatment_B.index), 'treatment_B_dummy'] = 1

# Creating an interaction term between privacy concerns and the treatment dummy
combined_data['privacy_treatment_interaction'] = combined_data['avg_privacy_concern'] * combined_data['treatment_B_dummy']

# Defining independent variables
X = combined_data[['avg_privacy_concern', 'treatment_B_dummy', 'privacy_treatment_interaction']]
X = sm.add_constant(X)  # Adds a constant term to the predictor

# Defining dependent variable
y = combined_data['num_rewards']

# Run the regression
model = sm.OLS(y, X).fit()

# Printing out the regression results
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:            num_rewards   R-squared:                       0.076
Model:                            OLS   Adj. R-squared:                  0.039
Method:                 Least Squares   F-statistic:                     2.055
Date:                Mon, 02 Oct 2023   Prob (F-statistic):              0.113
Time:                        19:45:15   Log-Likelihood:                -140.53
No. Observations:                  79   AIC:                             289.1
Df Residuals:                      75   BIC:                             298.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const         

### <b>H6b:The higher the perceived usefulness of personalization methods, the lower the demand for substantial rewards in return for engagement in personalization.</b> 

In [105]:
# Regression analysis for Treatment A
X_A = data_treatment_A[['avg_usefulness_A']]
X_A = sm.add_constant(X_A)
y_A = data_treatment_A['num_rewards_A']

model_A = sm.OLS(y_A, X_A).fit()

# Print the regression results for Treatment A
print("Results for Treatment A:")
print(model_A.summary())

Results for Treatment A:
                            OLS Regression Results                            
Dep. Variable:          num_rewards_A   R-squared:                       0.331
Model:                            OLS   Adj. R-squared:                  0.314
Method:                 Least Squares   F-statistic:                     18.84
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           0.000102
Time:                        19:45:15   Log-Likelihood:                -63.057
No. Observations:                  40   AIC:                             130.1
Df Residuals:                      38   BIC:                             133.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const          

In [106]:
# Regression analysis for Treatment B
X_B = data_treatment_B[['avg_usefulness_B']]
X_B = sm.add_constant(X_B)
y_B = data_treatment_B['num_rewards_B']

model_B = sm.OLS(y_B, X_B).fit()

# Printing the regression results for Treatment B
print("\nResults for Treatment B:")
print(model_B.summary())


Results for Treatment B:
                            OLS Regression Results                            
Dep. Variable:          num_rewards_B   R-squared:                       0.112
Model:                            OLS   Adj. R-squared:                  0.088
Method:                 Least Squares   F-statistic:                     4.687
Date:                Mon, 02 Oct 2023   Prob (F-statistic):             0.0369
Time:                        19:45:15   Log-Likelihood:                -69.530
No. Observations:                  39   AIC:                             143.1
Df Residuals:                      37   BIC:                             146.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const         

### <b>Results:</b>
In the context of Treatment A, the regression analysis was conducted to explore the relationship between the perceived usefulness of personalization methods and the demand for rewards in return for engagement in personalization. The dependent variable in this analysis was the number of rewards expected, while the independent variable was the average perceived usefulness score.

The regression model for Treatment A yielded an R-squared value of 0.331, indicating that approximately 33.1% of the variance in the number of rewards expected can be explained by the perceived usefulness of the personalization method. The coefficient for the average perceived usefulness was positive and statistically significant (coef = 0.5081, p < 0.001). This suggests that for every unit increase in the perceived usefulness score, there's an associated increase of approximately 0.5081 in the number of rewards expected.

This finding implies that respondents who found the personalization method in Treatment A more useful were also more inclined to expect more rewards in return for their engagement. The constant term in the regression equation was 0.5170, but it was not statistically significant (p = 0.347).

In summary, for Treatment A, there's a positive and significant relationship between the perceived usefulness of the personalization method and the number of rewards expected in return for engagement in personalization. This suggests that as respondents perceive the personalization method to be more useful, their expectations for rewards also increase.

Moreover, H6b; which posited that "The higher the perceived usefulness of personalization methods, the lower the demand for substantial rewards in return for engagement in personalization," the results from Treatment A do not support this hypothesis. Contrary to the expectation, the findings from Treatment A indicate that as the perceived usefulness of the personalization method increases, the demand for rewards also increases. Thus, for Treatment A, the hypothesis is refuted.


For Treatment B, the analysis aimed to test the hypothesis H6b, which postulated that as the perceived usefulness of personalization methods rises, there would be a diminished demand for substantial rewards in return for engagement in personalization. The regression results reveal an R-squared value of 0.112, suggesting that approximately 11.2% of the variance in the number of rewards expected can be explained by the perceived usefulness of the personalization method.

The coefficient for avg_usefulness_B is positive at 0.3130, with a standard error of 0.145. This coefficient is statistically significant at the 0.05 level (p = 0.037). This indicates that for every unit increase in the perceived usefulness of the personalization method in Treatment B, there is an associated increase of 0.313 in the number of rewards expected by the respondents.

Moreover, in the context of the posed hypothesis, H6b, the results from Treatment B do not align with this expectation. Instead, the data suggests that as respondents find the personalization method more useful, they also expect more rewards in return, similiar to Treatment A. Thus, for Treatment B, the hypothesis is not supported either.

## Exporting Tables for Word Doc:

### Standard deviation and mean of the scales

In [118]:
# Calculating means and standard deviations for each scale # ChatGPT
means_std = {
    'Perceived Usefulness (Treatment A)': {
        'Mean': data_treatment_A[['Q10A_num_use', 'Q11A_num_use', 'Q12A_num_use', 'Q13A_num_use', 'Q14A_num_use', 'Q15A_num_use']].mean(axis=1).mean(),
        'Standard Deviation': data_treatment_A[['Q10A_num_use', 'Q11A_num_use', 'Q12A_num_use', 'Q13A_num_use', 'Q14A_num_use', 'Q15A_num_use']].mean(axis=1).std()
    },
    'Perceived Usefulness (Treatment B)': {
        'Mean': data_treatment_B[['Q10B_num_use', 'Q11B_num_use', 'Q12B_num_use', 'Q13B_num_use', 'Q14B_num_use', 'Q15B_num_use']].mean(axis=1).mean(),
        'Standard Deviation': data_treatment_B[['Q10B_num_use', 'Q11B_num_use', 'Q12B_num_use', 'Q13B_num_use', 'Q14B_num_use', 'Q15B_num_use']].mean(axis=1).std()
    },
    'Privacy Concern (Treatment A)': {
        'Mean': data_treatment_A[['Q16A_num_priv', 'Q17A_num_priv', 'Q18A_num_priv', 'Q19A_num_priv', 'Q20A_num_priv']].mean(axis=1).mean(),
        'Standard Deviation': data_treatment_A[['Q16A_num_priv', 'Q17A_num_priv', 'Q18A_num_priv', 'Q19A_num_priv', 'Q20A_num_priv']].mean(axis=1).std()
    },
    'Privacy Concern (Treatment B)': {
        'Mean': data_treatment_B[['Q16B_num_priv', 'Q17B_num_priv', 'Q18B_num_priv', 'Q19B_num_priv', 'Q20B_num_priv']].mean(axis=1).mean(),
        'Standard Deviation': data_treatment_B[['Q16B_num_priv', 'Q17B_num_priv', 'Q18B_num_priv', 'Q19B_num_priv', 'Q20B_num_priv']].mean(axis=1).std()
    },
    'Inclination Towards Personalization': {
        'Mean': data_treatment_A[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']].mean(axis=1).mean(),  # Assuming data_treatment_A and data_treatment_B have the same values for these columns
        'Standard Deviation': data_treatment_A[['Q6_num_gen', 'Q7_num_gen', 'Q8_num_gen', 'Q9_num_gen']].mean(axis=1).std()
    }
}

# Printing the results
for scale, values in means_std.items():
    print(f"{scale}:")
    print(f"Mean: {values['Mean']:.2f}")
    print(f"Standard Deviation: {values['Standard Deviation']:.2f}")
    print("------")


Perceived Usefulness (Treatment A):
Mean: 4.35
Standard Deviation: 1.64
------
Perceived Usefulness (Treatment B):
Mean: 4.15
Standard Deviation: 1.66
------
Privacy Concern (Treatment A):
Mean: 3.74
Standard Deviation: 0.99
------
Privacy Concern (Treatment B):
Mean: 4.02
Standard Deviation: 0.99
------
Inclination Towards Personalization:
Mean: 3.54
Standard Deviation: 0.98
------


### Demographic distribution tables

In [107]:
# Age distribution for Treatment A
age_dist_A = data_treatment_A['Generation'].value_counts().reset_index()
age_dist_A.columns = ['Generation', 'Count']

# Age distribution for Treatment B
age_dist_B = data_treatment_B['Generation'].value_counts().reset_index()
age_dist_B.columns = ['Generation', 'Count']

# Education distribution for Treatment A
edu_dist_A = data_treatment_A['Education_Group'].value_counts().reset_index()
edu_dist_A.columns = ['Education Group', 'Count']

# Education distribution for Treatment B
edu_dist_B = data_treatment_B['Education_Group'].value_counts().reset_index()
edu_dist_B.columns = ['Education Group', 'Count']


In [108]:
# Gender distribution for Treatment A
gender_dist_A = data_treatment_A['Q2_num_demo'].value_counts().reset_index()
gender_dist_A.columns = ['Gender', 'Count']
gender_dist_A['Gender'] = gender_dist_A['Gender'].replace({1: 'Male', 2: 'Female'})

# Gender distribution for Treatment B
gender_dist_B = data_treatment_B['Q2_num_demo'].value_counts().reset_index()
gender_dist_B.columns = ['Gender', 'Count']
gender_dist_B['Gender'] = gender_dist_B['Gender'].replace({1: 'Male', 2: 'Female'})

In [109]:
# Merging the distributions for Treatment A
merged_A = age_dist_A.merge(edu_dist_A, how='outer', left_on='Generation', right_on='Education Group')
merged_A = merged_A.merge(gender_dist_A, how='outer', left_on='Generation', right_on='Gender')

# Merging the distributions for Treatment B
merged_B = age_dist_B.merge(edu_dist_B, how='outer', left_on='Generation', right_on='Education Group')
merged_B = merged_B.merge(gender_dist_B, how='outer', left_on='Generation', right_on='Gender')

In [110]:
# Exporting the tables to CSV
#merged_A.to_csv('Treatment_A_Distribution.csv', index=False)
#merged_B.to_csv('Treatment_B_Distribution.csv', index=False)

In [111]:
# Figuring out the most frequent expected rewards
def top_rewards(treatment_data, column_name):
    return treatment_data[column_name].str.split(',', expand=True).stack().value_counts().head(6)

top_rewards_A = top_rewards(data_treatment_A, 'Q22A_num_rew')
top_rewards_B = top_rewards(data_treatment_B, 'Q22B_num_rew')
top_rewards_overall = pd.concat([data_treatment_A['Q22A_num_rew'], data_treatment_B['Q22B_num_rew']]).str.split(',', expand=True).stack().value_counts().head(6)

In [112]:
print("Top Expected Rewards A:", top_rewards_A)
print("Top Expected Rewards B:", top_rewards_B)
print("Top Expected Rewards Overall:", top_rewards_overall)

Top Expected Rewards A: 2    33
1    23
4    20
3    18
5    15
6     3
dtype: int64
Top Expected Rewards B: 2    22
1    20
3    18
4    17
5    15
6     6
dtype: int64
Top Expected Rewards Overall: 2    55
1    43
4    37
3    36
5    30
6     9
dtype: int64


In [113]:
# Figuring out Most Frequently Disclosed Data Types
def top_data_types(treatment_data, column_name):
    return treatment_data[column_name].str.split(',', expand=True).stack().value_counts().head(6)

top_data_types_A = top_data_types(data_treatment_A, 'Q21A_num_data')
top_data_types_B = top_data_types(data_treatment_B, 'Q21B_num_data')
top_data_types_overall = pd.concat([data_treatment_A['Q21A_num_data'], data_treatment_B['Q21B_num_data']]).str.split(',', expand=True).stack().value_counts().head(6)

In [114]:
print("\nTop Data Types Disclosed A:", top_data_types_A)
print("Top Data Types Disclosed B:", top_data_types_B)
print("Top Data Types Disclosed Overall:", top_data_types_overall)


Top Data Types Disclosed A: 2    30
3    28
1    27
7    14
6    10
5     4
dtype: int64
Top Data Types Disclosed B: 2    30
1    28
3    21
7    19
6    11
5     7
dtype: int64
Top Data Types Disclosed Overall: 2    60
1    55
3    49
7    33
6    21
5    11
dtype: int64


In [115]:
# Privacy Concerns
avg_privacy_concern_A = data_treatment_A['avg_privacy_concern_A'].mean()
avg_privacy_concern_B = data_treatment_B['avg_privacy_concern_B'].mean()
avg_privacy_concern_overall = (avg_privacy_concern_A + avg_privacy_concern_B) / 2

# Perceived Usefulness
avg_usefulness_A = data_treatment_A['avg_usefulness_A'].mean()
avg_usefulness_B = data_treatment_B['avg_usefulness_B'].mean()
avg_usefulness_overall = (avg_usefulness_A + avg_usefulness_B) / 2

In [116]:
print("\nAverage Privacy Concern A:", avg_privacy_concern_A)
print("Average Privacy Concern B:", avg_privacy_concern_B)
print("Average Privacy Concern Overall:", avg_privacy_concern_overall)

print("\nAverage Perceived Usefulness A:", avg_usefulness_A)
print("Average Perceived Usefulness B:", avg_usefulness_B)
print("Average Perceived Usefulness Overall:", avg_usefulness_overall)


Average Privacy Concern A: 3.7399999999999998
Average Privacy Concern B: 4.015384615384615
Average Privacy Concern Overall: 3.8776923076923078

Average Perceived Usefulness A: 4.345833333333333
Average Perceived Usefulness B: 4.153846153846154
Average Perceived Usefulness Overall: 4.249839743589744
